language: node_js
node_js:
- '4.1'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_KEY
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    secure: aA2vByDCPZexWQfE7KFdoa3nb3UOB9eAi88MjzBHvqaUEwkSaVpMJi4Nt9/5NyFShOiKVE7erTN47MaM7JE6VWEQth2EHMxK0AzJHOkClqz6YLrRRSVFCRsm30n7DEWv5zZ6nxIvkW2UnMuEJEhfls04gCe2KJRA3Lcw53hHdYI=
