language: node_js
sudo: false
dist: trusty

cache:
  bundler: true
  directories:
  - node_modules
  - '$HOME/.sonar/cache'

branches:
  only:
  - master

before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_KEY

env:
- TEST_SUITE=lint
- TEST_SUITE=test

jdk:
  - oraclejdk8

script:
- "npm run $TEST_SUITE"
- sonar-scanner -Dsonar.sources=./src

addons:
  sonarqube:
    organization: "dbcdk-jph"
    token:
      secure: "ucN1+UEN06K76Op6r56uS3oDSuk0+bs1NfyFGlxAAABMjfE2Jl3dwyANCKz4YOrrR5Zqgl1b6AT7Xddft/HTIRlSERnYjJG2mebyO4vqGB+iArEPfn4lzhA7CZTPc37/UPC6L1aqBIPgle9kvnCesZR950Z85JhwWZtm556aSq9yhEESZWqRnurwDc41UnO0AUog3op5wygijOGgy4V/rd/o4PSCIspB68FR2QUvjlHKqgmcBTA2Gx4N0kOO7Df88Z1SBYLsuTagTU1J0+lRlKsFYGdIN8Zolaj8AK6dm5sVclt44n61VcW6XNA2U/g8AQcjNdAhhqhpOvDVNFty+HTXFc1qV/h1Dwk1dQyxHUaG6I986zRrkqaN+UHubn6KmkfVaI1WH8tsEWrEEFunesJYlW6ZNltW4VImscRyGO8nJI5I3Pe/ytx6fFgNcblwxPXaubO0LDTvHBQ1Z6TjqvnEsKwDC1LzF+VPphMq7Zx+t03JyZwqICaqy8IxvYwRmvQPRe8BIkdB7RisrP6xPlzLZlSXTxeaAlQv8k1tvF9UT9FdJn1aM+xl5Q4BmprZCOAIb+g0N+ekw336hMdndbNsMUoksFThQfIhtXGmcX2KjLXdmgiAfjpd6sh78s2snPvLC9BTafItQ31BDWdBBn3Cge/C8GeBju4rH4SnZ1A="

notifications:
  slack:
    secure: uXvdxzx6MnwBFkR3EFa/0DeBvVS1SZl/85UN58lWcHU7d8BjY6Kfhd8qAQ/lINIPyK3wHE0wMgtFkee+wcAskt04XOYiFZvWZIFbY3Eej+AVN6DCqpv8im7NXsh4m5DmAqJ3ktU6pH8+I1w6eGU2Rl3mZ/c7EDJquLJUOeMF7SVEHqSofxIuWDady1ErMmgMQjKjrutkxzvhJcG1kW7b445BWKGWQo7g6i7BV5M5nMcUJItD0urMbLLRn/pMCZ/7am87FckSaeXsIcLolkyzQQqImbN4/rBF4lnoQfH3N8a5yyGLaxu898KBe0FnTxYLeYONfAtJn/DKIsCvg8pNlp7AfXWjBifrbJ7K5fcevOzCSRrmFNiiyXFDD2+qqtkyLaMvgov1HNv8DavfRIAVXVAZRwrohaaoc7Ti+qBQVIGuBIP238h9jFi/wLjqAIGnu0/FSAk1+WkOYyBCt3DA1dEPmPu6UNd7bKwwNbjsriJqUQ4nX9wCIjngH3gS1u0YzY6mQxmB4ehgTdCm5HRFPQ8nUPK3O1nvPwkKs2HVLQD5OAHscSWUX1r7uJyjfgiJcBpE9tUkZbuNuf7A8/TLwVQymJ2ita+oyjf9BcZ3CgQ26NLUp5eAPyIMyXzKGbCwoa0y1lBoZ5pAHBsHfL9KqhF99VRRHYGZkIg4RbAkPJI=

