language: node_js
sudo: false
dist: trusty

cache:
  bundler: true
  directories:
    - node_modules

services:
  - redis-server

env:
  - SELENIUM_BROWSER=firefox CC=clang CXX=clang++ npm_config_clang=1

addons:
  firefox: "42.0"

branches:
  only:
    - master

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_KEY

script:
  - npm run lint
  - npm test
  - npm run features
