language: node_js
sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_KEY

script:
  - npm run lint
  - npm test
