language: node_js
sudo: false
dist: trusty

cache:
  bundler: true
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_KEY

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test

script: "npm run $TEST_SUITE"
