// Autogenerated!
const nock = require('nock');
module.exports = function campaignGroupWithContent(times) {
  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016",
      "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "review",
      "id": 1,
      "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature",
        "id": 10
      }]
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Posts/')
    .times(times)
    .query({"filter": "{\"limit\":5,\"skip\":0,\"counts\":\"comments\",\"where\":{\"groupid\":\"2\",\"markedAsDeleted\":null},\"order\":\"timeCreated DESC\",\"include\":[\"image\",{\"owner\":[\"image\"]},\"likes\",{\"relation\":\"review\",\"scope\":{\"include\":[\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}]}},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}]}"})
    .reply(200, [{
      "title": " ",
      "content": "asdasd",
      "timeCreated": "2016-07-22T07:02:49.000Z",
      "markedAsDeleted": null,
      "id": 2,
      "postownerid": 1,
      "postcontainergroupid": 2,
      "postid": null,
      "groupid": 2,
      "attachedReviewId": 0,
      "commentsCount": 0,
      "owner": {},
      "likes": []
    }, {
      "title": " ",
      "content": "halløj!",
      "timeCreated": "2016-07-21T13:28:11.000Z",
      "markedAsDeleted": null,
      "id": 1,
      "postownerid": 1,
      "postcontainergroupid": 2,
      "postid": null,
      "groupid": 2,
      "attachedReviewId": 0,
      "commentsCount": 1,
      "owner": {},
      "likes": []
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"group\"},\"include\":\"group\"}"})
    .reply(200, [{
      "campaignName": "fjolle kampagne",
      "startDate": "2016-07-20T00:00:00.000Z",
      "endDate": "2016-07-22T00:00:00.000Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "group",
      "id": 2,
      "workTypes": [],
      "group": {
        "name": "Skriv din egen historie",
        "description": "Dette er en test kampagne gruppe!",
        "colour": "blue",
        "timeCreated": "2016-07-25T09:03:23.000Z",
        "id": 136,
        "groupownerid": 323,
        "campaignGroupFK": 2,
        "campaign": {
          "campaignName": "fjolle kampagne",
          "startDate": "2016-07-20T00:00:00.000Z",
          "endDate": "2016-07-22T00:00:00.000Z",
          "logos": {
            "svg": "/sommerbogen-logo.svg",
            "small": "/sommerbogen-logo.png",
            "medium": "/sommerbogen-logo.png",
            "large": "/sommerbogen-logo.png"
          },
          "type": "group",
          "id": 2,
          "workTypes": []
        }
      }
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Groups/2')
    .times(times)
    .query({"filter": "{\"counts\":[\"posts\",\"members\"],\"include\":[{\"relation\":\"members\",\"scope\":{\"order\":\"id DESC\",\"include\":[\"image\"]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}},{\"relation\":\"coverImage\"}]}"})
    .reply(200, {
      "name": "string",
      "description": "string",
      "colour": "blue",
      "timeCreated": "2016-07-21T00:00:00.000Z",
      "id": 2,
      "groupownerid": 1,
      "campaignGroupFK": 2,
      "postsCount": 2,
      "membersCount": 1,
      "campaign": {
        "campaignName": "fjolle kampagne",
        "startDate": "2016-07-20T00:00:00.000Z",
        "endDate": "2016-07-22T00:00:00.000Z",
        "logos": {
          "svg": "/sommerbogen-logo.svg",
          "small": "/sommerbogen-logo.png",
          "medium": "/sommerbogen-logo.png",
          "large": "/sommerbogen-logo.png"
        },
        "type": "group",
        "id": 2,
        "workTypes": []
      },
      "members": [{
        "username": "bobby_hansen",
        "displayName": null,
        "favoriteLibrary": null,
        "description": null,
        "email": null,
        "phone": null,
        "created": "2016-07-22T09:24:55.650Z",
        "lastUpdated": "2016-07-22T09:24:55.650Z",
        "hasFilledInProfile": null,
        "birthday": null,
        "fullName": null,
        "palleid": null,
        "id": 2
      }],
      "owner": {}
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Comments/')
    .times(times)
    .query({"filter": "{\"limit\":1,\"skip\":0,\"order\":\"timeCreated DESC\",\"include\":[\"image\",\"review\",{\"owner\":[\"image\"]},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}],\"where\":{\"postid\":2}}"})
    .reply(200, []);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Comments/')
    .times(times)
    .query({"filter": "{\"limit\":1,\"skip\":0,\"order\":\"timeCreated DESC\",\"include\":[\"image\",\"review\",{\"owner\":[\"image\"]},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}],\"where\":{\"postid\":1}}"})
    .reply(200, [{
      "content": "adsf",
      "timeCreated": "2016-07-21T13:31:42.000Z",
      "id": 1,
      "commentownerid": 1,
      "commentcontainerpostid": 1,
      "postid": 1,
      "attachedReviewId": 0,
      "owner": {}
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/imageCollections/1/download/small')
    .times(times)

    .reply(200, {
      "container": "uxdev-biblo-imagebucket",
      "name": "8cd9a57753bb-4c58-9444-eea3c04aa0a7.jpg",
      "type": "image/jpeg",
      "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/8cd9a57753bb-4c58-9444-eea3c04aa0a7.jpg",
      "id": 1,
      "resolutionImageFileId": 1,
      "resolutionVideoFileId": null
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016",
      "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "review",
      "id": 1,
      "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature",
        "id": 10
      }]
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"group\"},\"include\":\"group\"}"})
    .reply(200, [{
      "campaignName": "fjolle kampagne",
      "startDate": "2016-07-20T00:00:00.000Z",
      "endDate": "2016-07-22T00:00:00.000Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "group",
      "id": 2,
      "workTypes": [],
      "group": {
        "name": "Skriv din egen historie",
        "description": "Dette er en test kampagne gruppe!",
        "colour": "blue",
        "timeCreated": "2016-07-25T09:03:23.000Z",
        "id": 136,
        "groupownerid": 323,
        "campaignGroupFK": 2,
        "campaign": {
          "campaignName": "fjolle kampagne",
          "startDate": "2016-07-20T00:00:00.000Z",
          "endDate": "2016-07-22T00:00:00.000Z",
          "logos": {
            "svg": "/sommerbogen-logo.svg",
            "small": "/sommerbogen-logo.png",
            "medium": "/sommerbogen-logo.png",
            "large": "/sommerbogen-logo.png"
          },
          "type": "group",
          "id": 2,
          "workTypes": []
        }
      }
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Posts/')
    .times(times)
    .query({"filter": "{\"limit\":5,\"skip\":0,\"counts\":\"comments\",\"where\":{\"groupid\":\"2\",\"markedAsDeleted\":null},\"order\":\"timeCreated DESC\",\"include\":[\"image\",{\"owner\":[\"image\"]},\"likes\",{\"relation\":\"review\",\"scope\":{\"include\":[\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}]}},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}]}"})
    .reply(200, [{
      "title": " ",
      "content": "asdasd",
      "timeCreated": "2016-07-22T07:02:49.000Z",
      "markedAsDeleted": null,
      "id": 2,
      "postownerid": 1,
      "postcontainergroupid": 2,
      "postid": null,
      "groupid": 2,
      "attachedReviewId": 0,
      "commentsCount": 0,
      "owner": {},
      "likes": []
    }, {
      "title": " ",
      "content": "halløj!",
      "timeCreated": "2016-07-21T13:28:11.000Z",
      "markedAsDeleted": null,
      "id": 1,
      "postownerid": 1,
      "postcontainergroupid": 2,
      "postid": null,
      "groupid": 2,
      "attachedReviewId": 0,
      "commentsCount": 1,
      "owner": {},
      "likes": []
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Groups/2')
    .times(times)
    .query({"filter": "{\"counts\":[\"posts\",\"members\"],\"include\":[{\"relation\":\"members\",\"scope\":{\"order\":\"id DESC\",\"include\":[\"image\"]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}},{\"relation\":\"coverImage\"}]}"})
    .reply(200, {
      "name": "string",
      "description": "string",
      "colour": "blue",
      "timeCreated": "2016-07-21T00:00:00.000Z",
      "id": 2,
      "groupownerid": 1,
      "campaignGroupFK": 2,
      "postsCount": 2,
      "membersCount": 1,
      "campaign": {
        "campaignName": "fjolle kampagne",
        "startDate": "2016-07-20T00:00:00.000Z",
        "endDate": "2016-07-22T00:00:00.000Z",
        "logos": {
          "svg": "/sommerbogen-logo.svg",
          "small": "/sommerbogen-logo.png",
          "medium": "/sommerbogen-logo.png",
          "large": "/sommerbogen-logo.png"
        },
        "type": "group",
        "id": 2,
        "workTypes": []
      },
      "members": [{
        "username": "bobby_hansen",
        "displayName": null,
        "favoriteLibrary": null,
        "description": null,
        "email": null,
        "phone": null,
        "created": "2016-07-22T09:24:55.650Z",
        "lastUpdated": "2016-07-22T09:24:55.650Z",
        "hasFilledInProfile": null,
        "birthday": null,
        "fullName": null,
        "palleid": null,
        "id": 2
      }],
      "owner": {}
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Comments/')
    .times(times)
    .query({"filter": "{\"limit\":1,\"skip\":0,\"order\":\"timeCreated DESC\",\"include\":[\"image\",\"review\",{\"owner\":[\"image\"]},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}],\"where\":{\"postid\":2}}"})
    .reply(200, []);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Comments/')
    .times(times)
    .query({"filter": "{\"limit\":1,\"skip\":0,\"order\":\"timeCreated DESC\",\"include\":[\"image\",\"review\",{\"owner\":[\"image\"]},{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}],\"where\":{\"postid\":1}}"})
    .reply(200, [{
      "content": "adsf",
      "timeCreated": "2016-07-21T13:31:42.000Z",
      "id": 1,
      "commentownerid": 1,
      "commentcontainerpostid": 1,
      "postid": 1,
      "attachedReviewId": 0,
      "owner": {}
    }]);
};
