// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function editoriallySelectedMaterialsWidget(times) {
  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200,
      "data": [{
        "dcTitle": ["Astro Boy"],
        "dcTitleFull": ["Astro Boy. Bind 1"],
        "titleSeries": ["Carlsen manga"],
        "publisher": ["Carlsen"],
        "description": ["Læses bagfra"],
        "extent": ["188 sider", "3 bind"],
        "format": ["alle illustreret"],
        "collection": ["870970-basis:25641647", "870970-basis:25641671", "870970-basis:25641728"],
        "collectionDetails": [{
          "accessType": ["physical"],
          "creator": ["Osamu Tezuka"],
          "pid": ["870970-basis:25641647"],
          "language": ["Dansk"],
          "title": ["Astro Boy"],
          "titleFull": ["Astro Boy"],
          "type": ["Tegneserie (bind 1)"],
          "workType": ["book"]
        }, {
          "accessType": ["physical"],
          "creator": ["Osamu Tezuka"],
          "pid": ["870970-basis:25641671"],
          "language": ["Dansk"],
          "title": ["Astro Boy"],
          "titleFull": ["Astro Boy"],
          "type": ["Tegneserie (bind 2)"],
          "workType": ["book"]
        }, {
          "accessType": ["physical"],
          "creator": ["Osamu Tezuka"],
          "pid": ["870970-basis:25641728"],
          "language": ["Dansk"],
          "title": ["Astro Boy"],
          "titleFull": ["Astro Boy"],
          "type": ["Tegneserie (bind 3)"],
          "workType": ["book"]
        }],
        "coverUrlFull": ["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=25641647&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=cca97c1c15ad7c7db8cc"],
        "dcLanguage": ["Dansk"],
        "accessType": ["physical"],
        "audience": ["børnematerialer"],
        "subjectDK5": ["sk"],
        "subjectDK5Text": ["Skønlitteratur"],
        "subjectDBCS": ["robotter", "science fiction"],
        "creator": ["Akira Himekawa"],
        "creatorAut": ["Osamu Tezuka"],
        "creatorSort": ["Tezuka, Osamu"],
        "contributor": ["Akira Himekawa"],
        "abstract": ["Tegneserie. Astro Boy er en robot, som alene er bygget med det formål at hjælpe og beskytte menneskene. Han er superstærk og helt speciel, fordi han er den første robot i verden der er skabt med et rigtigt hjerte"],
        "workType": ["book"],
        "type": ["Tegneserie (bind 1)"],
        "date": ["2005"]
      }]
    });
};
