// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function editoriallySelectedReviewsWidget(times) {
  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({"access_token": "", "where": "{\"markedAsDeleted\":null,\"or\":[{\"id\":3},{\"id\":4},{\"id\":5}]}"})
    .reply(200, {"count": 3});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"where\":{\"or\":[{\"id\":3},{\"id\":4},{\"id\":5}]}}"})
    .reply(200, [{
      "pid": "870970-basis:01210483",
      "libraryid": "714700",
      "worktype": "book",
      "content": "asdf",
      "created": "2016-07-22T08:23:01.000Z",
      "modified": "2016-07-22T08:23:01.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 3,
      "reviewownerid": 1
    }, {
      "pid": "870970-basis:29205000",
      "libraryid": "714700",
      "worktype": "book",
      "content": "adfs",
      "created": "2016-07-22T08:49:55.000Z",
      "modified": "2016-07-22T08:49:55.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 4,
      "reviewownerid": 1
    }, {
      "pid": "870970-basis:24695751",
      "libraryid": "714700",
      "worktype": "book",
      "content": "adsf",
      "created": "2016-07-22T09:11:39.000Z",
      "modified": "2016-07-22T09:11:39.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 5,
      "reviewownerid": 1
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016",
      "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "review",
      "id": 1,
      "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature",
        "id": 10
      }]
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":3,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"markedAsDeleted\":null,\"or\":[{\"id\":3},{\"id\":4},{\"id\":5}]}}"})
    .reply(200, [{
      "pid": "870970-basis:24695751",
      "libraryid": "714700",
      "worktype": "book",
      "content": "thisisareview1",
      "created": "2016-07-22T09:11:39.000Z",
      "modified": "2016-07-22T09:11:39.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 5,
      "reviewownerid": 1,
      "likes": [],
      "image": {
        "id": 18,
        "profileImageCollection": null,
        "groupCoverImageCollectionId": null,
        "postImageCollection": null,
        "commentImageCollection": null,
        "reviewImageCollection": 5,
        "resolutions": [{
          "size": "original",
          "id": 57,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf.jpg",
            "id": 88,
            "resolutionImageFileId": 57,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "thumbnail",
          "id": 61,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-thumbnail",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_thumbnail.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_thumbnail.jpg",
            "id": 92,
            "resolutionImageFileId": 61,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "small",
          "id": 62,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-small",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_small.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_small.jpg",
            "id": 93,
            "resolutionImageFileId": 62,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "medium",
          "id": 63,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-medium",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_medium.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_medium.jpg",
            "id": 94,
            "resolutionImageFileId": 63,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "large",
          "id": 64,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-large",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_large.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_large.jpg",
            "id": 95,
            "resolutionImageFileId": 64,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "large-square",
          "id": 65,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-large",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_large-square.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_large-square.jpg",
            "id": 96,
            "resolutionImageFileId": 65,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "medium-square",
          "id": 66,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-medium",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_medium-square.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_medium-square.jpg",
            "id": 97,
            "resolutionImageFileId": 66,
            "resolutionVideoFileId": null
          }
        }, {
          "size": "small-square",
          "id": 67,
          "videoCollectionResolutionId": null,
          "imageCollectionResolutionId": 18,
          "image": {
            "container": "uxdev-biblo-imagebucket-small",
            "name": "77cc675e509f-43be-b4fa-c110346e97bf_small-square.jpg",
            "type": "image/jpeg",
            "url": "https://uxdev-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/77cc675e509f-43be-b4fa-c110346e97bf_small-square.jpg",
            "id": 98,
            "resolutionImageFileId": 67,
            "resolutionVideoFileId": null
          }
        }]
      },
      "owner": {
        "displayName": "thisisthereviewauthor1"
      }
    }, {
      "pid": "870970-basis:29205000",
      "libraryid": "714700",
      "worktype": "book",
      "content": "thisisareview2",
      "created": "2016-07-22T08:49:55.000Z",
      "modified": "2016-07-22T08:49:55.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 4,
      "reviewownerid": 1,
      "likes": [],
      "owner": {
        "displayName": "thisisthereviewauthor2"
      }
    }, {
      "pid": "870970-basis:01210483",
      "libraryid": "714700",
      "worktype": "book",
      "content": "thisisareview3",
      "created": "2016-07-22T08:23:01.000Z",
      "modified": "2016-07-22T08:23:01.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 3,
      "reviewownerid": 1,
      "likes": [],
      "owner": {
        "displayName": "thisisthereviewauthor3"
      }
    }]);

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200,
      "data": [{
        "collection": ["870970-basis:01210483"],
        "dcTitle": ["Hobbyarbejder med hesteskosøm"],
        "workType": ["book"]
      }]
    });

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200,
      "data": [{
        "collection": ["870970-basis:29205000"],
        "dcTitle": ["Alt om Zlatan"],
        "workType": ["book"],
        "coverUrlFull": ["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=29205000&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=c7bda8a036e4d452517a"]
      }]
    });

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200,
      "data": [{
        "collection": ["870970-basis:24695751"],
        "dcTitle": ["Kaptajn Underhylers eventyr"],
        "workType": ["book"],
        "coverUrlFull": ["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=24695751&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=bbf8582653f7f9ac7828"]
      }]
    });
};
