// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function emmy(times) {
  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200, "data": [{
        "collection": ["870970-basis:29145253", "870970-basis:29384622", "870970-basis:29714746", "870970-basis:29566097"],
        "collectionDetails": [{
          "accessType": ["physical"], "creator": ["Mette Finderup"], "pid": ["870970-basis:29145253"],
          "language": ["Dansk"], "title": ["Emmy - konfirmationshys?"],
          "titleFull": ["Emmy - konfirmationshys? : hvem, mig?"], "type": ["Bog"], "workType": ["book"]
        }, {
          "accessType": ["online"], "creator": ["Mette Finderup"], "pid": ["870970-basis:29384622"],
          "language": ["Dansk"], "title": ["Emmy - konfirmationshys?"],
          "titleFull": ["Emmy - konfirmationshys? : hvem, mig???"], "type": ["Ebog"], "workType": ["book"]
        }, {
          "accessType": ["physical"], "creator": ["Mette Finderup"], "pid": ["870970-basis:29714746"],
          "language": ["Dansk"], "title": ["Emmy - konfirmationshys?"],
          "titleFull": ["Emmy - konfirmationshys? : hvem, mig???"], "type": ["Lydbog (cd-mp3)"],
          "workType": ["audiobook"]
        }, {
          "accessType": ["online"], "creator": ["Mette Finderup"], "pid": ["870970-basis:29566097"],
          "language": ["Dansk"], "title": ["Emmy - konfirmationshys?"],
          "titleFull": ["Emmy - konfirmationshys? : hvem, mig???"], "type": ["Lydbog (net)"], "workType": ["audiobook"]
        }], "acIdentifier": ["29145253|870970"], "identifierISBN": ["9788711410837"], "acSource": ["Bibliotekskatalog"],
        "dcTitle": ["Emmy - konfirmationshys?"], "dcTitleFull": ["Emmy - konfirmationshys? : hvem, mig?"],
        "creatorAut": ["Mette Finderup"], "creatorSort": ["Finderup, Mette"], "subjectDK5Text": ["Skønlitteratur"],
        "subjectDBCO": ["dagbøger"], "subjectDBCS": ["familien", "konfirmation", "piger", "sjove bøger", "venskab"],
        "subjectDBCN": ["for 10 år", "for 11 år", "for 12 år"], "subjectGenre": ["sjove bøger"], "subjectDK5": ["sk"],
        "abstract": ["Emmy skriver dagbog om tiden med konfirmationsforberedelse, konfirmation og andendagstur til Århus. Emmys forventninger til den store dag stemmer ikke altid overens med hendes mors, så hvordan mon det egentlig ender?"],
        "description": ["På ryggen: 0"], "descriptionSeries": ["0. del af: Emmy"], "audienceAge": ["fra 10 år"],
        "audience": ["børnematerialer"], "version": ["1. udgave, 2. oplag (2012)"], "publisher": ["Carlsen"],
        "contributorIll": ["Sussi Bech"], "date": ["2011"], "typeBibDKType": ["Bog"], "format": ["illustreret"],
        "extent": ["206 sider"], "languageISO6392": ["dan"], "dcLanguage": ["Dansk"], "accessType": ["physical"],
        "creator": ["Mette Finderup"], "pid": ["870970-basis:29145253"], "language": ["Dansk"],
        "title": ["Emmy - konfirmationshys?"], "titleFull": ["Emmy - konfirmationshys? : hvem, mig?"], "type": ["Bog"],
        "workType": ["book"]
      }]
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({
      "access_token": "",
      "where": "{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29145253\"},{\"pid\":\"870970-basis:29384622\"},{\"pid\":\"870970-basis:29714746\"},{\"pid\":\"870970-basis:29566097\"}]}]}"
    })
    .reply(200, {"count": 73});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}}],\"where\":{\"and\":[{\"reviewownerid\":39217},{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29145253\"},{\"pid\":\"870970-basis:29384622\"},{\"pid\":\"870970-basis:29714746\"},{\"pid\":\"870970-basis:29566097\"}]}]}}"})
    .reply(200, [{
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy skal snart konfirmeres men hendes mor har tænkt sig og holde hendes konfirmation hjemme men Emmy har helt andre planer. \r\n\r\nHvis du snart skal konfirmeres kan jeg klart anbefale og læse bogen, også hvis du ikke skal. \r\nBogen drejer sig om venskab, dumme forældre og konfirmation. ",
      "created": "2017-08-24T15:28:37.000Z", "modified": "2017-08-24T15:28:37.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": "2017-08-11T18:13:46.597Z",
        "lastUpdated": "2017-08-11T18:13:46.597Z", "hasFilledInProfile": true, "birthday": "2004-11-11T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "EMMYS KONFIRMATION\r\n\r\nEmmy skal snart konfirmeres og det er  mange ting der skal gøres inden den store dag. Emmy skal gå til præst, planlægge festen og finde den perfekte kjole.\r\n \r\nbogen er god fordi: det er spænende et at følge et helt forløb inden en konfirmation. den er god at læse inden man skal konfirmeres så den kan jeg anbefale ",
      "created": "2017-08-09T13:17:39.000Z", "modified": "2017-08-11T13:39:52.000Z", "rating": 3,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "phone": "12345678",
        "created": "2017-06-15T12:42:13.429Z", "lastUpdated": "2017-06-15T12:42:13.429Z", "hasFilledInProfile": true,
        "birthday": "2017-04-27T00:00:00.000Z", "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er sådan en bog du kan relatere til med skænderier med irreterende forældre men også venskab, familien og ikke mindst KONFIRMATIONEN!! \r\nEmmy er en pige på 13 år der skal til at konfirmeres og hun skriver det hele ned i en IKKE DAGBOG!!! men en Konfirmations bog som Emmy fik af sin mormor hendes dejlige mormor med runde kinder og briller. Emmys mor mener at hun bare er konfirmations hys men Emmy mener at hun bare vil have en fin konfirmation på Hvide okse. Men man kan ikke lige frem sige at det hele går Emmys vej men heldigvis har Emmy sine to bedste veninder Sasja og Kit som altid kan få hende til at grine.  \r\nJeg anbefaler HELT KLART! at man læser denne bog der er altid! dejligt at få en brandgod læse oplevelse i sin sommerferie 5/6 stjerner herfra =)",
      "created": "2017-08-01T09:16:11.000Z", "modified": "2017-08-01T09:16:11.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": null, "lastUpdated": null,
        "hasFilledInProfile": true, "birthday": null, "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er en 13 årig pige. Hun skal snart konfirmeres og hun glæder sig mega meget. Hun vil meget gerne have en perfekt konfirmation og hun vil gerne holde festen på den hvide okse. Men hendes mor har ikke råd fordi hendes mor og far er skilt og hendes far vil ikke betale noget, så hendes mor har lejet forsamlingshuset, men Emmy synes at der er ulækkert og så ender det med at det bliver hjemme i deres eget hus.",
      "created": "2017-07-17T15:54:56.000Z", "modified": "2017-07-17T15:54:56.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "phone": "12345678",
        "created": "2017-07-17T14:55:13.549Z", "lastUpdated": "2017-07-17T14:55:13.549Z", "hasFilledInProfile": true,
        "birthday": "2006-04-17T00:00:00.000Z", "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 58324, "groupCoverImageCollectionId": null,
          "postImageCollection": null, "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "1ef11a02d438-4273-81c0-d4425f9f774f.PNG",
              "type": "image/png",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119502, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_thumbnail.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_thumbnail.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119509, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_small.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_small.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119510, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_medium.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_medium.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119512, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_large.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_large.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119513, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_large-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_large-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163579, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_medium-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_medium-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163580, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_small-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_small-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163582, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er en pige, som mange andre. Hun har glædet sig i mange år til at blive konfirmeret. Hun finder så ud af at hun ikke er blevet døbt fordi hendes mor syndes at kristendom er noget pjat. Emmys fårældre er dog skilte og de skændes meget. Emmy vil jo bare havde den bedste konfirmation, men det går ikke så godt da hun høre at det skal holdes forsamlingshuset.\r\n\r\nEmmy serien er en virkelig god serie, og fyldt med masser små historie indimellem. den er beregnet til 10 - 14 årige     \r\n\r\n  ",
      "created": "2017-07-03T10:12:23.000Z", "modified": "2017-07-03T10:12:23.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": "2017-07-02T18:34:39.825Z",
        "lastUpdated": "2017-07-02T18:34:39.825Z", "hasFilledInProfile": true, "birthday": "2006-10-22T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 57601, "groupCoverImageCollectionId": null,
          "postImageCollection": null, "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5.JPG",
              "type": "image/jpeg",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116054, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_thumbnail.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_thumbnail.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116055, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_small.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_small.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116056, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116057, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_large.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_large.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116058, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_small-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_small-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162336, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162338, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_large-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_large-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162340, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy skal snart konfirmeres. Hun har glædet sig til det i flere år. En dag kommer hendes mormor på besøg og har en gave med. I starten virker Emmy en anelse skeptisk, men ændrer mening. Det viser sig pludselig at det ikke er så nemt at blive konfirmeret alligevel. Veninden Sasha er ikke blevet døbt fordi hendes mor mener at kristendommen undertrykker kvinder. Emmys skilte forældre skændes meget vedrørende hendes konfirmation. Hendes mor går rigtig meget op i at lave en god fest for hende og hendes far virker temmelig ligeglad. Da moren fortæller Emmy at hun har booket forsamlingshuset bliver Emmy så utilfreds at hun går lidt for vidt.\r\n\r\nBEMÆRK\r\nDenne bog er IKKE en del af Emmy-serien.  ",
      "created": "2017-07-02T15:58:37.000Z", "modified": "2017-07-02T15:58:37.000Z", "rating": 4,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "email": "email@email.com", "phone": "12345678", "created": "2016-07-29T15:06:36.756Z",
        "lastUpdated": "2016-07-29T15:06:36.756Z", "hasFilledInProfile": true, "birthday": "2007-05-17T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy bogen handler om en piger der snart skal kornfirmeres. Hun får en dagbog af sin mormor, til at skrive om sin kornfirmation. Hun vil gerne holde hendes kornfirmation hos Hvide okse, men det må hun ikke for sin mor. Så derfor lejer hendes mor forsamlingshuset i stedet for. Men det vil Emmy ikke. Samtidigt må hendes vindene Shasa ikke blive kornfirmeret fordi hun ikke er døbt. Emmy og hendes anden vindene Kit, ville hjælpe Sasha. Emmy's mormor har hendes kornfirmation og bryllups kjole, som Sasha låner. Men den ender godt.",
      "created": "2017-06-29T18:56:16.000Z", "modified": "2017-06-29T18:56:16.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description", "email": "email@email.com",
        "phone": "12345678", "created": "2017-06-29T18:16:11.433Z", "lastUpdated": "2017-06-29T18:16:11.433Z",
        "hasFilledInProfile": true, "birthday": "2007-05-13T00:00:00.000Z", "fullName": "Full Name",
        "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy handler om en 13-årige pige, som får en dagbog af sin mormor, som mormoren tænker at hun kan skrive konfirmationsdagbog i. Hendes forældre er skilt og Emmy har en storebror på 17 år der er rigtig irriterende. Da Emmy får dagbogen er der cirka 8 måneder til hun skal konfirmeres. Hun ved allerede hvordan festen skal være. Men da hun fortæller sin mor, hvordan hun gerne vil have det og ikke får det som hun vil, beslutter hun sig for at ringe til det sted, hvor hun gerne vil holde festen. Altså at snyde sin mor. Men hendes mor opdager det og så bliver det bare holdt hjemme hos hendes mor. Emmy bliver ked af at festen ikke bliver helt som hun havde tænkt, men hun får det bedre efter et lille stykke tid.\r\nDet ender med at hun får en god konfirmation alligevel.\r\nBogen er nok mest til piger fra 9 til 12 år.\r\nDen er meget spændende men ikke helt i top top.\r\n",
      "created": "2016-08-17T17:16:31.000Z", "modified": "2016-08-17T17:16:31.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.dk", "phone": "12345678", "created": "2016-08-17T17:02:55.087Z",
        "lastUpdated": "2016-08-17T17:02:55.087Z", "hasFilledInProfile": true, "birthday": "2005-05-16T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 1234, "groupCoverImageCollectionId": null, "postImageCollection": null,
          "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 1234,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "e3cb9335da14-4649-8c09-4ff9b1651837.JPG",
              "type": "image/jpeg",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 1234, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_thumbnail.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_thumbnail.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 1234, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_small.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_small.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47118, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_medium.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_medium.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47119, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_large.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_large.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47120, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_small-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_small-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137602, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_medium-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_medium-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137604, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_large-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_large-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137606, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "bogen handler om Emmy som er 13 år og snart skal konfirmeres. hele hendes klasse glæder sig rigtig meget. emmy har 2 gode veninder som heder kit og sasha. emmy vil gerne have den helt rigtige konfirmation, hun vil gerne have at festen er på hvide okse, en lang ønske liste og en fin kjole, men hendes forældre er skilt og hendes far vil ikke give penge, så de har ikke så mange penge. så hendes mor vil ikke have at det bliver på hvide okse fordi at det koster rigtig mange penge så det skal blive i et forsamlingshus men det er emmy ikke glad for....",
      "created": "2016-08-10T18:49:27.000Z", "modified": "2016-08-10T18:49:27.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "created": "2016-06-26T07:49:12.248Z",
        "lastUpdated": "2016-06-26T07:49:12.248Z", "hasFilledInProfile": true, "birthday": "2003-01-11T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Bogen handler om 13-årige Emmy, der snart skal konfirmeres. Alle fra hendes klasse er virkeligt meget oppe at køre over det, og Emmy selv har også store forventninger. Hendes fest skal SELVFØLGELIG holdes på en fin kro, og hun skal have den flotteste kjole og de bedste gaver. Desværre er hendes forældre skilt, og hendes far går ikke rigtigt op i det. Emmys mor går til gengæld meget op i det, og hun synes at Emmys fest skal holdes i forsamlingshuset, hvilket Emmy IKKE har lyst til...",
      "created": "2016-07-31T17:24:25.000Z", "modified": "2016-07-31T17:24:25.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": null, "lastUpdated": null,
        "hasFilledInProfile": true, "birthday": "2003-12-21T23:00:00.000Z", "fullName": "Full Name",
        "palleid": null, "id": 1234
      }
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29145253\"},{\"pid\":\"870970-basis:29384622\"},{\"pid\":\"870970-basis:29714746\"},{\"pid\":\"870970-basis:29566097\"}]}]}}"})
    .reply(200, [{
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy skal snart konfirmeres men hendes mor har tænkt sig og holde hendes konfirmation hjemme men Emmy har helt andre planer. \r\n\r\nHvis du snart skal konfirmeres kan jeg klart anbefale og læse bogen, også hvis du ikke skal. \r\nBogen drejer sig om venskab, dumme forældre og konfirmation. ",
      "created": "2017-08-24T15:28:37.000Z", "modified": "2017-08-24T15:28:37.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": "2017-08-11T18:13:46.597Z",
        "lastUpdated": "2017-08-11T18:13:46.597Z", "hasFilledInProfile": true, "birthday": "2004-11-11T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "EMMYS KONFIRMATION\r\n\r\nEmmy skal snart konfirmeres og det er  mange ting der skal gøres inden den store dag. Emmy skal gå til præst, planlægge festen og finde den perfekte kjole.\r\n \r\nbogen er god fordi: det er spænende et at følge et helt forløb inden en konfirmation. den er god at læse inden man skal konfirmeres så den kan jeg anbefale ",
      "created": "2017-08-09T13:17:39.000Z", "modified": "2017-08-11T13:39:52.000Z", "rating": 3,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "phone": "12345678",
        "created": "2017-06-15T12:42:13.429Z", "lastUpdated": "2017-06-15T12:42:13.429Z", "hasFilledInProfile": true,
        "birthday": "2017-04-27T00:00:00.000Z", "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er sådan en bog du kan relatere til med skænderier med irreterende forældre men også venskab, familien og ikke mindst KONFIRMATIONEN!! \r\nEmmy er en pige på 13 år der skal til at konfirmeres og hun skriver det hele ned i en IKKE DAGBOG!!! men en Konfirmations bog som Emmy fik af sin mormor hendes dejlige mormor med runde kinder og briller. Emmys mor mener at hun bare er konfirmations hys men Emmy mener at hun bare vil have en fin konfirmation på Hvide okse. Men man kan ikke lige frem sige at det hele går Emmys vej men heldigvis har Emmy sine to bedste veninder Sasja og Kit som altid kan få hende til at grine.  \r\nJeg anbefaler HELT KLART! at man læser denne bog der er altid! dejligt at få en brandgod læse oplevelse i sin sommerferie 5/6 stjerner herfra =)",
      "created": "2017-08-01T09:16:11.000Z", "modified": "2017-08-01T09:16:11.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": null, "lastUpdated": null,
        "hasFilledInProfile": true, "birthday": null, "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er en 13 årig pige. Hun skal snart konfirmeres og hun glæder sig mega meget. Hun vil meget gerne have en perfekt konfirmation og hun vil gerne holde festen på den hvide okse. Men hendes mor har ikke råd fordi hendes mor og far er skilt og hendes far vil ikke betale noget, så hendes mor har lejet forsamlingshuset, men Emmy synes at der er ulækkert og så ender det med at det bliver hjemme i deres eget hus.",
      "created": "2017-07-17T15:54:56.000Z", "modified": "2017-07-17T15:54:56.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "phone": "12345678",
        "created": "2017-07-17T14:55:13.549Z", "lastUpdated": "2017-07-17T14:55:13.549Z", "hasFilledInProfile": true,
        "birthday": "2006-04-17T00:00:00.000Z", "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 58324, "groupCoverImageCollectionId": null,
          "postImageCollection": null, "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "1ef11a02d438-4273-81c0-d4425f9f774f.PNG",
              "type": "image/png",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119502, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_thumbnail.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_thumbnail.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119509, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_small.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_small.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119510, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_medium.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_medium.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119512, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14732,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "1ef11a02d438-4273-81c0-d4425f9f774f_large.PNG",
              "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_large.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 119513, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_large-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_large-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163579, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_medium-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_medium-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163580, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14732, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "1ef11a02d438-4273-81c0-d4425f9f774f_small-square.PNG", "type": "image/png",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/1ef11a02d438-4273-81c0-d4425f9f774f_small-square.PNG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 163582, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy er en pige, som mange andre. Hun har glædet sig i mange år til at blive konfirmeret. Hun finder så ud af at hun ikke er blevet døbt fordi hendes mor syndes at kristendom er noget pjat. Emmys fårældre er dog skilte og de skændes meget. Emmy vil jo bare havde den bedste konfirmation, men det går ikke så godt da hun høre at det skal holdes forsamlingshuset.\r\n\r\nEmmy serien er en virkelig god serie, og fyldt med masser små historie indimellem. den er beregnet til 10 - 14 årige     \r\n\r\n  ",
      "created": "2017-07-03T10:12:23.000Z", "modified": "2017-07-03T10:12:23.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": "2017-07-02T18:34:39.825Z",
        "lastUpdated": "2017-07-02T18:34:39.825Z", "hasFilledInProfile": true, "birthday": "2006-10-22T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 57601, "groupCoverImageCollectionId": null,
          "postImageCollection": null, "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5.JPG",
              "type": "image/jpeg",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116054, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_thumbnail.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_thumbnail.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116055, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_small.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_small.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116056, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116057, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 14317,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_large.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_large.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 116058, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_small-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_small-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162336, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_medium-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162338, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 14317, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "f9e96ad180c2-4ba5-969a-cf2fde677ff5_large-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/f9e96ad180c2-4ba5-969a-cf2fde677ff5_large-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 162340, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy skal snart konfirmeres. Hun har glædet sig til det i flere år. En dag kommer hendes mormor på besøg og har en gave med. I starten virker Emmy en anelse skeptisk, men ændrer mening. Det viser sig pludselig at det ikke er så nemt at blive konfirmeret alligevel. Veninden Sasha er ikke blevet døbt fordi hendes mor mener at kristendommen undertrykker kvinder. Emmys skilte forældre skændes meget vedrørende hendes konfirmation. Hendes mor går rigtig meget op i at lave en god fest for hende og hendes far virker temmelig ligeglad. Da moren fortæller Emmy at hun har booket forsamlingshuset bliver Emmy så utilfreds at hun går lidt for vidt.\r\n\r\nBEMÆRK\r\nDenne bog er IKKE en del af Emmy-serien.  ",
      "created": "2017-07-02T15:58:37.000Z", "modified": "2017-07-02T15:58:37.000Z", "rating": 4,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "email": "email@email.com", "phone": "12345678", "created": "2016-07-29T15:06:36.756Z",
        "lastUpdated": "2016-07-29T15:06:36.756Z", "hasFilledInProfile": true, "birthday": "2007-05-17T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy bogen handler om en piger der snart skal kornfirmeres. Hun får en dagbog af sin mormor, til at skrive om sin kornfirmation. Hun vil gerne holde hendes kornfirmation hos Hvide okse, men det må hun ikke for sin mor. Så derfor lejer hendes mor forsamlingshuset i stedet for. Men det vil Emmy ikke. Samtidigt må hendes vindene Shasa ikke blive kornfirmeret fordi hun ikke er døbt. Emmy og hendes anden vindene Kit, ville hjælpe Sasha. Emmy's mormor har hendes kornfirmation og bryllups kjole, som Sasha låner. Men den ender godt.",
      "created": "2017-06-29T18:56:16.000Z", "modified": "2017-06-29T18:56:16.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "loanerId": "0123456789", "pincode": "1234"},
        "description": "description", "email": "email@email.com",
        "phone": "12345678", "created": "2017-06-29T18:16:11.433Z", "lastUpdated": "2017-06-29T18:16:11.433Z",
        "hasFilledInProfile": true, "birthday": "2007-05-13T00:00:00.000Z", "fullName": "Full Name",
        "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Emmy handler om en 13-årige pige, som får en dagbog af sin mormor, som mormoren tænker at hun kan skrive konfirmationsdagbog i. Hendes forældre er skilt og Emmy har en storebror på 17 år der er rigtig irriterende. Da Emmy får dagbogen er der cirka 8 måneder til hun skal konfirmeres. Hun ved allerede hvordan festen skal være. Men da hun fortæller sin mor, hvordan hun gerne vil have det og ikke får det som hun vil, beslutter hun sig for at ringe til det sted, hvor hun gerne vil holde festen. Altså at snyde sin mor. Men hendes mor opdager det og så bliver det bare holdt hjemme hos hendes mor. Emmy bliver ked af at festen ikke bliver helt som hun havde tænkt, men hun får det bedre efter et lille stykke tid.\r\nDet ender med at hun får en god konfirmation alligevel.\r\nBogen er nok mest til piger fra 9 til 12 år.\r\nDen er meget spændende men ikke helt i top top.\r\n",
      "created": "2016-08-17T17:16:31.000Z", "modified": "2016-08-17T17:16:31.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": "2016-08-17T17:02:55.087Z",
        "lastUpdated": "2016-08-17T17:02:55.087Z", "hasFilledInProfile": true, "birthday": "2005-05-16T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234, "image": {
          "id": 1234, "profileImageCollection": 48999, "groupCoverImageCollectionId": null, "postImageCollection": null,
          "commentImageCollection": null, "reviewImageCollection": null, "resolutions": [{
            "size": "original", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxdev-biblo-imagebucket", "name": "e3cb9335da14-4649-8c09-4ff9b1651837.JPG",
              "type": "image/jpeg",
              "url": "https://uxdev-biblo-imagebucket.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47116, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "thumbnail", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-thumbnail",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_thumbnail.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-thumbnail.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_thumbnail.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47117, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-small", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_small.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_small.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47118, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-medium", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_medium.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_medium.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47119, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large", "id": 1234, "videoCollectionResolutionId": null, "imageCollectionResolutionId": 5991,
            "image": {
              "container": "uxprod-biblo-imagebucket-large", "name": "e3cb9335da14-4649-8c09-4ff9b1651837_large.JPG",
              "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_large.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 47120, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "small-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-small",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_small-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_small-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137602, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "medium-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-medium",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_medium-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-medium.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_medium-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137604, "resolutionVideoFileId": null,
              "scans": []
            }
          }, {
            "size": "large-square", "id": 1234, "videoCollectionResolutionId": null,
            "imageCollectionResolutionId": 5991, "image": {
              "container": "uxprod-biblo-imagebucket-large",
              "name": "e3cb9335da14-4649-8c09-4ff9b1651837_large-square.JPG", "type": "image/jpeg",
              "url": "https://uxprod-biblo-imagebucket-large.s3-eu-west-1.amazonaws.com/e3cb9335da14-4649-8c09-4ff9b1651837_large-square.JPG",
              "id": 1234, "postPdfAttachment": null, "resolutionImageFileId": 137606, "resolutionVideoFileId": null,
              "scans": []
            }
          }]
        }
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "bogen handler om Emmy som er 13 år og snart skal konfirmeres. hele hendes klasse glæder sig rigtig meget. emmy har 2 gode veninder som heder kit og sasha. emmy vil gerne have den helt rigtige konfirmation, hun vil gerne have at festen er på hvide okse, en lang ønske liste og en fin kjole, men hendes forældre er skilt og hendes far vil ikke give penge, så de har ikke så mange penge. så hendes mor vil ikke have at det bliver på hvide okse fordi at det koster rigtig mange penge så det skal blive i et forsamlingshus men det er emmy ikke glad for....",
      "created": "2016-08-10T18:49:27.000Z", "modified": "2016-08-10T18:49:27.000Z", "rating": 6,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName", "favoriteLibrary": {"libraryId": "123456"},
        "description": "description", "created": "2016-06-26T07:49:12.248Z",
        "lastUpdated": "2016-06-26T07:49:12.248Z", "hasFilledInProfile": true, "birthday": "2003-01-11T00:00:00.000Z",
        "fullName": "Full Name", "palleid": null, "id": 1234
      }
    }, {
      "pid": "870970-basis:29145253", "libraryId": "123456", "worktype": "book",
      "content": "Bogen handler om 13-årige Emmy, der snart skal konfirmeres. Alle fra hendes klasse er virkeligt meget oppe at køre over det, og Emmy selv har også store forventninger. Hendes fest skal SELVFØLGELIG holdes på en fin kro, og hun skal have den flotteste kjole og de bedste gaver. Desværre er hendes forældre skilt, og hendes far går ikke rigtigt op i det. Emmys mor går til gengæld meget op i det, og hun synes at Emmys fest skal holdes i forsamlingshuset, hvilket Emmy IKKE har lyst til...",
      "created": "2016-07-31T17:24:25.000Z", "modified": "2016-07-31T17:24:25.000Z", "rating": 5,
      "markedAsDeleted": null, "palleid": null, "id": 1234, "idreviewownerid": 1234, "likes": [], "owner": {
        "username": "username", "displayName": "displayName",
        "favoriteLibrary": {"libraryId": "123456", "pincode": "1234", "loanerId": "0123456789"},
        "description": "description",
        "email": "email@email.com", "phone": "12345678", "created": null, "lastUpdated": null,
        "hasFilledInProfile": true, "birthday": "2003-12-21T23:00:00.000Z", "fullName": "Full Name",
        "palleid": null, "id": 1234
      }
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016", "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z", "logos": {
        "svg": "/sommerbogen-logo.svg", "small": "/sommerbogen-logo.png", "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      }, "type": "review", "id": 1234,
      "workTypes": [{"worktype": "book", "id": 1234}, {"worktype": "audiobook", "id": 1234}, {
        "worktype": "literature", "id": 1234
      }]
    }, {
      "campaignName": "Vild Med Film 2016", "startDate": "2016-07-15T22:00:00.000Z",
      "endDate": "2016-09-30T21:59:59.000Z", "logos": {
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=BjJ1xzJ8",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=emXGcxp5",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=OyLHdCzn",
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/VildmedfilmLOGO%20solid.svg"
      }, "type": "review", "id": 1234, "workTypes": [{"worktype": "movie", "id": 1234}]
    }, {
      "campaignName": "Sommerbogen 2017", "startDate": "2017-06-12T22:00:00.000Z",
      "endDate": "2017-08-26T21:59:59.000Z", "logos": {
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/sommerbogen-logo.svg",
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=5f95nbCt",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=aAgdIqi0",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=kI0CJooV"
      }, "type": "review", "id": 1234,
      "workTypes": [{"worktype": "book", "id": 1234}, {"worktype": "other", "id": 1234}, {
        "worktype": "audiobook", "id": 1234
      }, {"worktype": "literature", "id": 1234}]
    }, {
      "campaignName": "Vild med film 2017", "startDate": "2017-08-31T22:00:00.000Z",
      "endDate": "2017-09-21T21:59:59.000Z", "logos": {
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/VildmedfilmLOGO%20solid_0.svg",
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=ovrp6MLC",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=ntb0gLew",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=Hs5ErkZ7"
      }, "type": "review", "id": 1234, "workTypes": [{"worktype": "movie", "id": 1234}]
    }]);

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .reply(200, {
      "statusCode": 200, "data": [{
        "pid": ["870970-basis:29384622"],
        "hasOnlineAccess": ["https://ereolen.dk/ting/object/870970-basis:29384622", "https://ereolen.dk/ting/object/870970-basis:29384622"]
      }]
    });

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .reply(200, {
      "statusCode": 200, "data": [{
        "pid": ["870970-basis:29566097"],
        "hasOnlineAccess": ["https://ereolen.dk/ting/object/870970-basis:29566097", "https://ereolen.dk/ting/object/870970-basis:29566097"]
      }]
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get(/\/api\/imageCollections\/\d*\/download\/small/)
    .times(3)
    .reply(200, {
      "container": "uxprod-biblo-imagebucket-small",
      "name": "841a751e0c75-4afb-a197-d9cd056b1cf6_small.png",
      "type": "image/png",
      "url": "https://uxprod-biblo-imagebucket-small.s3-eu-west-1.amazonaws.com/841a751e0c75-4afb-a197-d9cd056b1cf6_small.png",
      "id": 1234,
      "resolutionImageFileId": 30308,
      "resolutionVideoFileId": null
    });
};
