// Autogenerated!
const nock = require('nock');
module.exports = function emptyUser(times) {
  nock('http://localhost:3000', {encodedQueryParams: true})
    .post('/api/Profiles/checkIfUserExists')
    .times(times)
    .reply(200, {"username": "bobby_hansen", "exists": true});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .post('/api/Profiles/unilogin')
    .times(times)
    .reply(200, {
      "id": "RXeubF64O4cHD6ORsGeBrBRo5BNHExVFtTGp4i3tUOzgenCGPHy3oFMH3Tr9BF5X",
      "ttl": 30000000,
      "created": "2016-06-24T09:14:19.180Z",
      "profileId": 42727,
      "profile": {
        "username": "bobby_hansen",
        "displayName": null,
        "favoriteLibrary": null,
        "description": null,
        "email": null,
        "phone": null,
        "created": "2016-06-21T13:06:56.733Z",
        "lastUpdated": "2016-06-21T13:06:56.733Z",
        "hasFilledInProfile": null,
        "birthday": null,
        "fullName": null,
        "palleid": null,
        "id": 42727
      }
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Quarantines/42727/check-if-profile-is-quarantined')
    .times(times)
    .reply(200, {"quarantined": false});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Profiles/42727')
    .times(times)
    .query({
      "filter": "{\"include\":[\"image\",\"communityRoles\"]}",
      "access_token": "RXeubF64O4cHD6ORsGeBrBRo5BNHExVFtTGp4i3tUOzgenCGPHy3oFMH3Tr9BF5X"
    })
    .reply(200, {
      "username": "bobby_hansen",
      "displayName": null,
      "favoriteLibrary": null,
      "description": null,
      "email": null,
      "phone": null,
      "created": "2016-06-21T13:06:56.733Z",
      "lastUpdated": "2016-06-21T13:06:56.733Z",
      "hasFilledInProfile": null,
      "birthday": null,
      "fullName": null,
      "palleid": null,
      "id": 42727,
      "communityRoles": [{"name": "member", "id": 1}]
    });

  nock('https://dynamodb.eu-west-1.amazonaws.com:443', {encodedQueryParams: true})
    .post('/')
    .times(times)
    .reply(200, {"Count": 0, "Items": [], "ScannedCount": 48});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Quarantines/42727/check-if-profile-is-quarantined')
    .times(times)
    .reply(200, {"quarantined": false});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Profiles/42727')
    .times(times)
    .query({
      "filter": "{\"include\":[\"image\",\"communityRoles\"]}",
      "access_token": "RXeubF64O4cHD6ORsGeBrBRo5BNHExVFtTGp4i3tUOzgenCGPHy3oFMH3Tr9BF5X"
    })
    .reply(200, {
      "username": "bobby_hansen",
      "displayName": null,
      "favoriteLibrary": null,
      "description": null,
      "email": null,
      "phone": null,
      "created": "2016-06-21T13:06:56.733Z",
      "lastUpdated": "2016-06-21T13:06:56.733Z",
      "hasFilledInProfile": null,
      "birthday": null,
      "fullName": null,
      "palleid": null,
      "id": 42727,
      "communityRoles": [{"name": "member", "id": 1}]
    });

  nock('https://dynamodb.eu-west-1.amazonaws.com:443', {encodedQueryParams: true})
    .post('/')
    .times(times)
    .reply(200, {"Count": 0, "Items": [], "ScannedCount": 48});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Quarantines/42727/check-if-profile-is-quarantined')
    .times(times)
    .reply(200, {"quarantined": false});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Profiles/42727')
    .times(times)
    .query({
      "filter": "{\"include\":[\"image\",\"communityRoles\"]}",
      "access_token": "RXeubF64O4cHD6ORsGeBrBRo5BNHExVFtTGp4i3tUOzgenCGPHy3oFMH3Tr9BF5X"
    })
    .reply(200, {
      "username": "bobby_hansen",
      "displayName": null,
      "favoriteLibrary": null,
      "description": null,
      "email": null,
      "phone": null,
      "created": "2016-06-21T13:06:56.733Z",
      "lastUpdated": "2016-06-21T13:06:56.733Z",
      "hasFilledInProfile": null,
      "birthday": null,
      "fullName": null,
      "palleid": null,
      "id": 42727,
      "communityRoles": [{"name": "member", "id": 1}]
    });

  nock('https://dynamodb.eu-west-1.amazonaws.com:443', {encodedQueryParams: true})
    .post('/')
    .times(times)
    .reply(200, {"Count": 0, "Items": [], "ScannedCount": 48});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Quarantines/42727/check-if-profile-is-quarantined')
    .times(times)
    .reply(200, {"quarantined": false});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Profiles/42727')
    .times(times)
    .query({
      "filter": "{\"include\":[\"image\",\"communityRoles\"]}",
      "access_token": "RXeubF64O4cHD6ORsGeBrBRo5BNHExVFtTGp4i3tUOzgenCGPHy3oFMH3Tr9BF5X"
    })
    .reply(200, {
      "username": "bobby_hansen",
      "displayName": null,
      "favoriteLibrary": null,
      "description": null,
      "email": null,
      "phone": null,
      "created": "2016-06-21T13:06:56.733Z",
      "lastUpdated": "2016-06-21T13:06:56.733Z",
      "hasFilledInProfile": null,
      "birthday": null,
      "fullName": null,
      "palleid": null,
      "id": 42727,
      "communityRoles": [{"name": "member", "id": 1}]
    });

  nock('https://dynamodb.eu-west-1.amazonaws.com:443', {encodedQueryParams: true})
    .post('/')
    .times(times)
    .reply(200, {"Count": 0, "Items": [], "ScannedCount": 48});
};
