// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function ProfileFormSave(times) {
  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bibli"})
    .reply(200, {
      "responseHeader": {
        "q": "Bibli", "version": "0.2.0", "build": "789", "time": 3, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bibl"})
    .reply(200, {
      "responseHeader": {
        "q": "Bibl", "version": "0.2.0", "build": "789", "time": 6, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bibliote"})
    .reply(200, {
      "responseHeader": {
        "q": "Bibliote", "version": "0.2.0", "build": "789", "time": 4, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bibliot"})
    .reply(200, {
      "responseHeader": {
        "q": "Bibliot", "version": "0.2.0", "build": "789", "time": 4, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket", "version": "0.2.0", "build": "789", "time": 1, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "Greve", "væsensnavn": "Greve Bibliotek", "adresse": "Hovedbiblioteket Portalen",
            "navn": "Greve Bibliotek", "postnr": "2670", "kortnavn": "Greve", "latitude": "55.5983284",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "725300"
          }
        }, {
          "suggestion": {
            "by": "Dragør", "væsensnavn": "Dragør Bibliotekerne", "adresse": "Halvejen 3",
            "navn": "Biblioteket i Hollænderhallen", "postnr": "2791", "kortnavn": "Hollænderhallen",
            "latitude": "55.594183", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715501"
          }
        }, {
          "suggestion": {
            "by": "Kibæk", "væsensnavn": "Herning Bibliotekerne", "adresse": "Solbakken 30",
            "navn": "Biblioteket i Kibæk", "postnr": "6933", "kortnavn": "Biblioteket i Kibæk", "latitude": "56.027692",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765708"
          }
        }, {
          "suggestion": {
            "by": "Herning", "væsensnavn": "Herning Bibliotekerne", "adresse": "Østergade 8",
            "navn": "Biblioteket i Herning", "postnr": "7400", "kortnavn": "Biblioteket i Herning",
            "latitude": "56.136", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765700"
          }
        }, {
          "suggestion": {
            "by": "Sydals", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Knøs Gård 1",
            "navn": "Biblioteket Hørup", "postnr": "6470", "kortnavn": "Hørup", "latitude": "54.9141624",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754008"
          }
        }, {
          "suggestion": {
            "by": "Helsingør", "væsensnavn": "Helsingør Kommunes Biblioteker", "adresse": "Allegade 2",
            "navn": "Biblioteket Kulturværftet", "postnr": "3000", "kortnavn": "Helsingør Bibliotek",
            "latitude": "56.0377711", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "721700"
          }
        }, {
          "suggestion": {
            "by": "Gråsten", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Ahlefeldvej 4",
            "navn": "Biblioteket Gråsten", "postnr": "6300", "kortnavn": "Gråsten", "latitude": "54.919526",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754004"
          }
        }, {
          "suggestion": {
            "by": "Vildbjerg", "væsensnavn": "Herning Bibliotekerne", "adresse": "Kirkegade 7",
            "navn": "Biblioteket i Vildbjerg", "postnr": "7480", "kortnavn": "Biblioteket i Vildbjerg",
            "latitude": "56.1980564", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765705"
          }
        }, {
          "suggestion": {
            "by": "Nordborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Løjtertoft 7",
            "navn": "Biblioteket Nordborg", "postnr": "6430", "kortnavn": "Nordborg", "latitude": "55.056813",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754006"
          }
        }, {
          "suggestion": {
            "by": "Broager", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Storegade 6 A",
            "navn": "Biblioteket Broager", "postnr": "6310", "kortnavn": "Broager", "latitude": "54.889586",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754002"
          }
        }, {
          "suggestion": {
            "by": "Aulum", "væsensnavn": "Herning Bibliotekerne", "adresse": "Markedspladsen 1",
            "navn": "Biblioteket i Aulum", "postnr": "7490", "kortnavn": "Biblioteket i Aulum", "latitude": "56.265547",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765707"
          }
        }, {
          "suggestion": {
            "by": "Stenløse", "væsensnavn": "Egedal Bibliotekerne", "adresse": "Rådhustorvet 2",
            "navn": "Biblioteket i Stenløse Kulturhus", "postnr": "3660", "kortnavn": "Stenløse Bibliotek",
            "latitude": "55.768226", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "724002"
          }
        }, {
          "suggestion": {
            "by": "Støvring", "væsensnavn": "Rebild Bibliotekerne", "adresse": "Grangårdsvej 13",
            "navn": "Biblioteket Støvring", "postnr": "9530", "kortnavn": "Rebild Bibliotekerne",
            "latitude": "56.8889672", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "784000"
          }
        }, {
          "suggestion": {
            "by": "Brøndby", "væsensnavn": "Brøndby-Bibliotekerne", "adresse": "Nygårds Plads 31",
            "navn": "Biblioteket i Kilden", "postnr": "2605", "kortnavn": "BrøndbyBibliotekerne",
            "latitude": "55.667581", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715300"
          }
        }, {
          "suggestion": {
            "by": "Sønderborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Kongevej 19-27",
            "navn": "Biblioteket Sønderborg", "postnr": "6400", "kortnavn": "Sønderborg", "latitude": "54.910175",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754000"
          }
        }, {
          "suggestion": {
            "by": "Kastrup", "væsensnavn": "Tårnby Kommunebiblioteker", "adresse": "Kamillevej 10",
            "navn": "Hovedbiblioteket", "postnr": "2770", "kortnavn": "Tårnby Kommunebiblioteker",
            "latitude": "55.632321", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "718500"
          }
        }, {
          "suggestion": {
            "by": "Dragør", "væsensnavn": "Dragør Bibliotekerne", "adresse": "Vestgrønningen 18-20",
            "navn": "Biblioteket i Dragør", "postnr": "2791", "kortnavn": "Dragør Bibliotek", "latitude": "55.5932177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "715500"
          }
        }, {
          "suggestion": {
            "by": "Sunds", "væsensnavn": "Herning Bibliotekerne", "adresse": "Sunds Hovedgade 50-52",
            "navn": "Biblioteket i Sunds", "postnr": "7451", "kortnavn": "Biblioteket i Sunds",
            "latitude": "56.2041173", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765704"
          }
        }, {
          "suggestion": {
            "by": "Augustenborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Kettingvej 1 a",
            "navn": "Biblioteket Augustenborg", "postnr": "6440", "kortnavn": "Augustenborg", "latitude": "54.9466504",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754001"
          }
        }], "numFound": 74
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bib"})
    .reply(200, {
      "responseHeader": {
        "q": "Bib", "version": "0.2.0", "build": "789", "time": 9, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteke"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteke", "version": "0.2.0", "build": "789", "time": 3, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "Greve", "væsensnavn": "Greve Bibliotek", "adresse": "Hovedbiblioteket Portalen",
            "navn": "Greve Bibliotek", "postnr": "2670", "kortnavn": "Greve", "latitude": "55.5983284",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "725300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Aalborg Bibliotekerne", "adresse": "", "navn": "Bogbus 3", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "785142"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Aalborg Bibliotekerne", "adresse": "", "navn": "Bogbus 2", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "785141"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Hjørring Bibliotekerne", "adresse": "", "navn": "Lørslev", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "786017"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Dragør Bibliotekerne", "adresse": "", "navn": "Lokalarkiv", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715502"
          }
        }, {
          "suggestion": {
            "by": "Dragør", "væsensnavn": "Dragør Bibliotekerne", "adresse": "Halvejen 3",
            "navn": "Biblioteket i Hollænderhallen", "postnr": "2791", "kortnavn": "Hollænderhallen",
            "latitude": "55.594183", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715501"
          }
        }, {
          "suggestion": {
            "by": "Kibæk", "væsensnavn": "Herning Bibliotekerne", "adresse": "Solbakken 30",
            "navn": "Biblioteket i Kibæk", "postnr": "6933", "kortnavn": "Biblioteket i Kibæk", "latitude": "56.027692",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765708"
          }
        }, {
          "suggestion": {
            "by": "Herning", "væsensnavn": "Herning Bibliotekerne", "adresse": "Østergade 8",
            "navn": "Biblioteket i Herning", "postnr": "7400", "kortnavn": "Biblioteket i Herning",
            "latitude": "56.136", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765700"
          }
        }, {
          "suggestion": {
            "by": "Sydals", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Knøs Gård 1",
            "navn": "Biblioteket Hørup", "postnr": "6470", "kortnavn": "Hørup", "latitude": "54.9141624",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754008"
          }
        }, {
          "suggestion": {
            "by": "Helsingør", "væsensnavn": "Helsingør Kommunes Biblioteker", "adresse": "Allegade 2",
            "navn": "Biblioteket Kulturværftet", "postnr": "3000", "kortnavn": "Helsingør Bibliotek",
            "latitude": "56.0377711", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "721700"
          }
        }, {
          "suggestion": {
            "by": "Gråsten", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Ahlefeldvej 4",
            "navn": "Biblioteket Gråsten", "postnr": "6300", "kortnavn": "Gråsten", "latitude": "54.919526",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754004"
          }
        }, {
          "suggestion": {
            "by": "Vildbjerg", "væsensnavn": "Herning Bibliotekerne", "adresse": "Kirkegade 7",
            "navn": "Biblioteket i Vildbjerg", "postnr": "7480", "kortnavn": "Biblioteket i Vildbjerg",
            "latitude": "56.1980564", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765705"
          }
        }, {
          "suggestion": {
            "by": "Nordborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Løjtertoft 7",
            "navn": "Biblioteket Nordborg", "postnr": "6430", "kortnavn": "Nordborg", "latitude": "55.056813",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754006"
          }
        }, {
          "suggestion": {
            "by": "Broager", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Storegade 6 A",
            "navn": "Biblioteket Broager", "postnr": "6310", "kortnavn": "Broager", "latitude": "54.889586",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754002"
          }
        }, {
          "suggestion": {
            "by": "Aulum", "væsensnavn": "Herning Bibliotekerne", "adresse": "Markedspladsen 1",
            "navn": "Biblioteket i Aulum", "postnr": "7490", "kortnavn": "Biblioteket i Aulum", "latitude": "56.265547",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765707"
          }
        }, {
          "suggestion": {
            "by": "Nakskov", "væsensnavn": "LollandBibliotekerne", "adresse": "Søvej 8",
            "navn": "LollandBibliotekerne, Nakskov", "postnr": "4900", "kortnavn": "Nakskov", "latitude": "54.834957",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "736000"
          }
        }, {
          "suggestion": {
            "by": "Stenløse", "væsensnavn": "Egedal Bibliotekerne", "adresse": "Rådhustorvet 2",
            "navn": "Biblioteket i Stenløse Kulturhus", "postnr": "3660", "kortnavn": "Stenløse Bibliotek",
            "latitude": "55.768226", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "724002"
          }
        }, {
          "suggestion": {
            "by": "Brøndby", "væsensnavn": "Brøndby-Bibliotekerne", "adresse": "Nygårds Plads 31",
            "navn": "Biblioteket i Kilden", "postnr": "2605", "kortnavn": "BrøndbyBibliotekerne",
            "latitude": "55.667581", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715300"
          }
        }, {
          "suggestion": {
            "by": "Støvring", "væsensnavn": "Rebild Bibliotekerne", "adresse": "Grangårdsvej 13",
            "navn": "Biblioteket Støvring", "postnr": "9530", "kortnavn": "Rebild Bibliotekerne",
            "latitude": "56.8889672", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "784000"
          }
        }], "numFound": 405
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket Go"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket Go", "version": "0.2.0", "build": "789", "time": 2, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket G"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket G", "version": "0.2.0", "build": "789", "time": 1, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Gråsten", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Ahlefeldvej 4",
            "navn": "Biblioteket Gråsten", "postnr": "6300", "kortnavn": "Gråsten", "latitude": "54.919526",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754004"
          }
        }, {
          "suggestion": {
            "by": "Søborg", "væsensnavn": "Gladsaxe Bibliotekerne", "adresse": "Søborg Hovedgade 220",
            "navn": "Gladsaxe Bibliotekerne, Hovedbiblioteket", "postnr": "2860", "kortnavn": "Gladsaxe Hovedbibliotek",
            "latitude": "55.7423172", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715900"
          }
        }, {
          "suggestion": {
            "by": "Aalborg SØ", "væsensnavn": "Aalborg Bibliotekerne", "adresse": "Grønlands Torv 1, st.",
            "navn": "Biblioteket Grønlands Torv", "postnr": "9210", "kortnavn": "Grønlands Torv",
            "latitude": "57.0230115", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "785104"
          }
        }, {
          "suggestion": {
            "by": "Nykøbing F", "væsensnavn": "Guldborgsund-bibliotekerne", "adresse": "Kongens Gade 43",
            "navn": "Hovedbiblioteket", "postnr": "4800", "kortnavn": "Guldborgsund", "latitude": "54.7693089",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "737600"
          }
        }, {
          "suggestion": {
            "by": "Tåstrup", "væsensnavn": "Høje-Taastrup Kommunes Biblioteker",
            "adresse": "Gadehaveskolen,\r\nGadehavegårdsvej 1,", "navn": "Gadehavebiblioteket", "postnr": "2630",
            "kortnavn": "Gadehavebiblioteket", "latitude": "55.6520198", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "716904"
          }
        }, {
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }, {
          "suggestion": {
            "by": "Hellerup", "væsensnavn": "Gentofte Bibliotekerne", "adresse": "Ahlmanns Alle 6",
            "navn": "Gentofte Bibliotekerne. Hovedbiblioteket", "postnr": "2900", "kortnavn": "Gentofte Bibliotekerne",
            "latitude": "55.737459", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715700"
          }
        }], "numFound": 7
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket Godth"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket Godth", "version": "0.2.0", "build": "789", "time": 1, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket Godt"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket Godt", "version": "0.2.0", "build": "789", "time": 1, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblio"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblio", "version": "0.2.0", "build": "789", "time": 6, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Bibliotek"})
    .reply(200, {
      "responseHeader": {
        "q": "Bibliotek", "version": "0.2.0", "build": "789", "time": 4, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "", "væsensnavn": "Odder Bibliotek", "adresse": "", "navn": "Tunø Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "772705"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Norddjurs Biblioteker", "adresse": "", "navn": "Anholt Bibliotek", "postnr": "",
            "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "770702"
          }
        }, {
          "suggestion": {
            "by": "Nærum", "væsensnavn": "Rudersdal Bibliotekerne", "adresse": "Biblioteksalleen 3",
            "navn": "Nærum Bibliotek", "postnr": "2850", "kortnavn": "Nærum Bibliotek", "latitude": "55.816177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "723002"
          }
        }, {
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Asaa",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781051"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Jerslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781055"
          }
        }, {
          "suggestion": {
            "by": "Hørsholm", "væsensnavn": "Hørsholm Bibliotek", "adresse": "Bibliotekstorvet 1",
            "navn": "Hørsholm Bibliotek", "postnr": "2970", "kortnavn": "Hørsholm Bibliotek", "latitude": "55.880699",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "722300"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Serritslev",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781059"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Øster Brønderslev", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781063"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Stenum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781060"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Manna",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781058"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Agersted",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781050"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Thise",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781062"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Flauenskjold", "postnr": "", "kortnavn": "", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781052"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Sterup",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781061"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hellum",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781054"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads mandag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781056"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "",
            "navn": "Det Mobile Bibliotek - Klokkerholm. Holdeplads onsdag", "postnr": "", "kortnavn": "",
            "latitude": "", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "781057"
          }
        }, {
          "suggestion": {
            "by": "", "væsensnavn": "Brønderslev Bibliotek", "adresse": "", "navn": "Det Mobile Bibliotek - Hallund",
            "postnr": "", "kortnavn": "", "latitude": "", "geolokation": {"lat": 0, "lng": 0},
            "bibliotekstype": "Folkebibliotek", "id": "781053"
          }
        }, {
          "suggestion": {
            "by": "Svendborg", "væsensnavn": "Svendborg Bibliotek", "adresse": "Biblioteksvej 1, Landet,",
            "navn": "Landet Bibliotek", "postnr": "5700", "kortnavn": "Landet Bibliotek", "latitude": "54.998477",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "747904"
          }
        }], "numFound": 551
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket "})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket", "version": "0.2.0", "build": "789", "time": 2, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Herlev", "væsensnavn": "Herlev Bibliotek", "adresse": "Biblioteket Kilden\r\nDildhaven 40",
            "navn": "Hjortespring Bibliotek", "postnr": "2730", "kortnavn": "Biblioteket Kilden", "latitude": "",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "716301"
          }
        }, {
          "suggestion": {
            "by": "Greve", "væsensnavn": "Greve Bibliotek", "adresse": "Hovedbiblioteket Portalen",
            "navn": "Greve Bibliotek", "postnr": "2670", "kortnavn": "Greve", "latitude": "55.5983284",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "725300"
          }
        }, {
          "suggestion": {
            "by": "Dragør", "væsensnavn": "Dragør Bibliotekerne", "adresse": "Halvejen 3",
            "navn": "Biblioteket i Hollænderhallen", "postnr": "2791", "kortnavn": "Hollænderhallen",
            "latitude": "55.594183", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715501"
          }
        }, {
          "suggestion": {
            "by": "Kibæk", "væsensnavn": "Herning Bibliotekerne", "adresse": "Solbakken 30",
            "navn": "Biblioteket i Kibæk", "postnr": "6933", "kortnavn": "Biblioteket i Kibæk", "latitude": "56.027692",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765708"
          }
        }, {
          "suggestion": {
            "by": "Herning", "væsensnavn": "Herning Bibliotekerne", "adresse": "Østergade 8",
            "navn": "Biblioteket i Herning", "postnr": "7400", "kortnavn": "Biblioteket i Herning",
            "latitude": "56.136", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765700"
          }
        }, {
          "suggestion": {
            "by": "Sydals", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Knøs Gård 1",
            "navn": "Biblioteket Hørup", "postnr": "6470", "kortnavn": "Hørup", "latitude": "54.9141624",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754008"
          }
        }, {
          "suggestion": {
            "by": "Helsingør", "væsensnavn": "Helsingør Kommunes Biblioteker", "adresse": "Allegade 2",
            "navn": "Biblioteket Kulturværftet", "postnr": "3000", "kortnavn": "Helsingør Bibliotek",
            "latitude": "56.0377711", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "721700"
          }
        }, {
          "suggestion": {
            "by": "Gråsten", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Ahlefeldvej 4",
            "navn": "Biblioteket Gråsten", "postnr": "6300", "kortnavn": "Gråsten", "latitude": "54.919526",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754004"
          }
        }, {
          "suggestion": {
            "by": "Vildbjerg", "væsensnavn": "Herning Bibliotekerne", "adresse": "Kirkegade 7",
            "navn": "Biblioteket i Vildbjerg", "postnr": "7480", "kortnavn": "Biblioteket i Vildbjerg",
            "latitude": "56.1980564", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765705"
          }
        }, {
          "suggestion": {
            "by": "Nordborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Løjtertoft 7",
            "navn": "Biblioteket Nordborg", "postnr": "6430", "kortnavn": "Nordborg", "latitude": "55.056813",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754006"
          }
        }, {
          "suggestion": {
            "by": "Broager", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Storegade 6 A",
            "navn": "Biblioteket Broager", "postnr": "6310", "kortnavn": "Broager", "latitude": "54.889586",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754002"
          }
        }, {
          "suggestion": {
            "by": "Aulum", "væsensnavn": "Herning Bibliotekerne", "adresse": "Markedspladsen 1",
            "navn": "Biblioteket i Aulum", "postnr": "7490", "kortnavn": "Biblioteket i Aulum", "latitude": "56.265547",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "765707"
          }
        }, {
          "suggestion": {
            "by": "Stenløse", "væsensnavn": "Egedal Bibliotekerne", "adresse": "Rådhustorvet 2",
            "navn": "Biblioteket i Stenløse Kulturhus", "postnr": "3660", "kortnavn": "Stenløse Bibliotek",
            "latitude": "55.768226", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "724002"
          }
        }, {
          "suggestion": {
            "by": "Støvring", "væsensnavn": "Rebild Bibliotekerne", "adresse": "Grangårdsvej 13",
            "navn": "Biblioteket Støvring", "postnr": "9530", "kortnavn": "Rebild Bibliotekerne",
            "latitude": "56.8889672", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "784000"
          }
        }, {
          "suggestion": {
            "by": "Brøndby", "væsensnavn": "Brøndby-Bibliotekerne", "adresse": "Nygårds Plads 31",
            "navn": "Biblioteket i Kilden", "postnr": "2605", "kortnavn": "BrøndbyBibliotekerne",
            "latitude": "55.667581", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "715300"
          }
        }, {
          "suggestion": {
            "by": "Sønderborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Kongevej 19-27",
            "navn": "Biblioteket Sønderborg", "postnr": "6400", "kortnavn": "Sønderborg", "latitude": "54.910175",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754000"
          }
        }, {
          "suggestion": {
            "by": "Kastrup", "væsensnavn": "Tårnby Kommunebiblioteker", "adresse": "Kamillevej 10",
            "navn": "Hovedbiblioteket", "postnr": "2770", "kortnavn": "Tårnby Kommunebiblioteker",
            "latitude": "55.632321", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "718500"
          }
        }, {
          "suggestion": {
            "by": "Dragør", "væsensnavn": "Dragør Bibliotekerne", "adresse": "Vestgrønningen 18-20",
            "navn": "Biblioteket i Dragør", "postnr": "2791", "kortnavn": "Dragør Bibliotek", "latitude": "55.5932177",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "715500"
          }
        }, {
          "suggestion": {
            "by": "Sunds", "væsensnavn": "Herning Bibliotekerne", "adresse": "Sunds Hovedgade 50-52",
            "navn": "Biblioteket i Sunds", "postnr": "7451", "kortnavn": "Biblioteket i Sunds",
            "latitude": "56.2041173", "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek",
            "id": "765704"
          }
        }, {
          "suggestion": {
            "by": "Augustenborg", "væsensnavn": "Biblioteket Sønderborg", "adresse": "Kettingvej 1 a",
            "navn": "Biblioteket Augustenborg", "postnr": "6440", "kortnavn": "Augustenborg", "latitude": "54.9466504",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "754001"
          }
        }], "numFound": 74
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket God"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket God", "version": "0.2.0", "build": "789", "time": 2, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": "Biblioteket Godthåb"})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket Godthåb", "version": "0.2.0", "build": "789", "time": 2, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });

  nock('http://0.entity-suggest-cisterne.xp.prod.mcp1-proxy.dbc.dk:80', {encodedQueryParams: true})
    .get('/entity-suggest/library')
    .times(times)
    .query({"lt": "folkebibliotek", "query": /.+/})
    .reply(200, {
      "responseHeader": {
        "q": "Biblioteket Godthå", "version": "0.2.0", "build": "789", "time": 2, "ab-id": "1",
        "args": {"lt": "folkebibliotek", "gl": null}, "svn-revision": "114407"
      }, "response": {
        "suggestions": [{
          "suggestion": {
            "by": "Frederiksberg", "væsensnavn": "Biblioteket Frederiksberg", "adresse": "Godthåbsvej 85 A",
            "navn": "Biblioteket Godthåbsvej", "postnr": "2000", "kortnavn": "Godthåbsvej", "latitude": "55.688685",
            "geolokation": {"lat": 0, "lng": 0}, "bibliotekstype": "Folkebibliotek", "id": "714703"
          }
        }], "numFound": 1
      }
    });
};


