// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function fangerneDragsholm(times) {
  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)
    .reply(200, {
      "statusCode": 200,
      "data": [{
        "dcTitle": ["Fangerne på Dragsholm"],
        "dcTitleFull": ["Fangerne på Dragsholm"],
        "publisher": ["Branner og Korch"],
        "descriptionSeries": ["Samhørende: Fangerne på Dragsholm ; Flugten fra Dragsholm ; Fra Dragsholm til Lusekoften"],
        "extent": ["119 sider"],
        "collection": ["870970-basis:05999790", "870970-basis:09340564"],
        "collectionDetails": [{
          "accessType": ["physical"],
          "creator": ["Brita Hartz"],
          "pid": ["870970-basis:05999790"],
          "language": ["Dansk"],
          "title": ["Fangerne på Dragsholm"],
          "titleFull": ["Fangerne på Dragsholm"],
          "type": ["Bog"],
          "workType": ["book"]
        }, {
          "accessType": ["physical"],
          "creator": ["Brita Hartz"],
          "pid": ["870970-basis:09340564"],
          "language": ["Dansk"],
          "title": ["Fangerne på Dragsholm"],
          "titleFull": ["Fangerne på Dragsholm"],
          "type": ["Lydbog (bånd)"],
          "workType": ["audiobook"]
        }],
        "dcLanguage": ["Dansk"],
        "accessType": ["physical"],
        "audienceAge": ["fra 12 år"],
        "audience": ["børnematerialer"],
        "subjectDK5": ["sk"],
        "subjectDK5Text": ["Skønlitteratur"],
        "subjectDBCN": ["for 12 år", "for 13 år", "for 14 år"],
        "subjectDBCS": ["1500-1599", "Brahe, Sophie", "Danmark", "Dragsholm Slot", "Jarlen af Bothwell", "historie"],
        "creator": ["Brita Hartz"],
        "creatorAut": ["Brita Hartz"],
        "creatorSort": ["Hartz, Brita"],
        "abstract": ["I 1573 sidder drengen Terkel fængslet på Dragsholm Slot, hvor hans søster Marie får arbejde. Samme sted opholder Jarlen af Bothwell sig som statsfange, og ved jarlens og Maries hjælp lykkes det Terkel at flygte"],
        "workType": ["book"],
        "type": ["Bog"],
        "date": ["1983"]
      }]
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({
      "access_token": "",
      "where": "{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05999790\"}]}]}"
    })
    .reply(200, {"count": 11});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05999790\"}]}]}}"})
    .reply(200, [{
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 1,
      "reviewownerid": 1,
      "likes": [],
      "owner": {}
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 2,
      "reviewownerid": 2,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 3,
      "reviewownerid": 3,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 4,
      "reviewownerid": 4,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 5,
      "reviewownerid": 5,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 6,
      "reviewownerid": 6,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 7,
      "reviewownerid": 7,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 8,
      "reviewownerid": 8,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 9,
      "reviewownerid": 9,
      "likes": []
    }, {
      "pid": "870970-basis:05999790",
      "libraryid": "733000",
      "worktype": "book",
      "content": "yes uyes ueas",
      "created": "2017-07-04T12:24:21.000Z",
      "modified": "2017-07-04T12:24:21.000Z",
      "rating": 1,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 10,
      "reviewownerid": 10,
      "likes": []
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016",
      "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "review",
      "id": 1,
      "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature",
        "id": 10
      }]
    }]);

  nock('http://uxscrum-i02.dbc.dk:8889', {encodedQueryParams: true})
    .get('/menu/main')
    .times(times)
    .query({"_format":"json"})
    .reply(200, [{"link":{"url":{"external":false,"uri":"/grupper"},"title":"Grupper","description":"Se alle grupper","enabled":true,"weight":"0","options":[],"meta_data":{"entity_id":"4"},"provider":"menu_link_content"},"subtree":[],"depth":1,"options":[]}]);

  nock('http://uxscrum-i02.dbc.dk:8889', {encodedQueryParams: true})
    .get('/menu/footer')
    .times(times)
    .query({"_format":"json"})
    .reply(200, [{"link":{"url":{"external":true,"uri":"http://bibliotek.dk"},"title":"Søg på bibliotek.dk","description":null,"enabled":true,"weight":"-50","options":{"external":true},"meta_data":{"entity_id":"2"},"provider":"menu_link_content"},"subtree":[],"depth":1,"options":[]},{"link":{"url":{"external":false,"uri":""},"title":"Læs vores guide til god søgning på nettet","description":null,"enabled":true,"weight":"-49","options":{"fragment":"what-ever"},"meta_data":{"entity_id":"3"},"provider":"menu_link_content"},"subtree":[],"depth":1,"options":[]},{"link":{"url":{"external":true,"uri":"http://google.com"},"title":"Søg på google","description":null,"enabled":true,"weight":"-48","options":{"external":true},"meta_data":{"entity_id":"1"},"provider":"menu_link_content"},"subtree":[],"depth":1,"options":[]}]);
};
