// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function Fuglejagten(times) {
  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/work/')
    .times(times)
    .reply(200, {
      "statusCode": 200, "data": [{
        "dcTitle": ["Fuglejagten"], "dcTitleFull": ["Fuglejagten"], "publisher": ["SF Film"],
        "description": ["Produktion: Nimbus Film (Danmark) etc., 2012"], "extent": ["89 min."],
        "format": ["1 dvd-video"], "collection": ["870970-basis:29410895", "870970-basis:29926492"],
        "collectionDetails": [{
          "accessType": ["physical"], "pid": ["870970-basis:29410895"], "title": ["Fuglejagten"],
          "titleFull": ["Fuglejagten"], "type": ["Dvd"], "workType": ["movie"]
        }, {
          "accessType": ["online"], "pid": ["870970-basis:29926492"], "title": ["Fuglejagten"],
          "titleFull": ["Fuglejagten"], "type": ["Film (net)"], "workType": ["movie"]
        }],
        "coverUrlFull": ["https://moreinfo.addi.dk/2.11/more_info_get.php?lokalid=29410895&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=6f5e90b4f5df32ba59dd"],
        "dcLanguage": ["Dansk"], "accessType": ["physical"], "audienceAge": ["fra 7 år"],
        "audience": ["børnematerialer"],
        "audienceMedieraad": ["Mærkning: Tilladt for alle men frarådes børn under 7 år"], "subjectDK5": ["77.74"],
        "subjectDK5Text": ["Børnefilm"],
        "subjectDBCN": ["for 10 år", "for 11 år", "for 12 år", "for 13 år", "for 7 år", "for 8 år", "for 9 år"],
        "subjectDBCO": ["danske film"],
        "subjectDBCS": ["far-søn forholdet", "fugle", "komedier", "ornitologer", "snyderi", "venskab"],
        "creatorDrt": ["Christian Dyekjær"],
        "creatorSort": ["Dyekjær, Christian", "Dyekjær, Christian", "Damgaard-Sørensen, Mette", "Søborg, Morten"],
        "contributorAct": ["Oliver Methling Søndergård", "Lars Brygmann", "Georg Hvidtfeldt Treschow", "Jesper Asholt", "Nicolas Bro", "Charlotte Fich", "Jesper Langberg"],
        "abstract": ["Victor er fugleinteresseret ganske som sin far, og sammen deler de også sorgen over, at mor har fundet en anden mand. Som også er ornitolog og har en søn, som er Victors rival, når det gælder om at fotografere den mest sjældne fugl. Victor snyder for at vinde!"],
        "workType": ["movie"], "type": ["Dvd"], "date": ["2012"]
      }]
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016", "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z", "logos": {
        "svg": "/sommerbogen-logo.svg", "small": "/sommerbogen-logo.png", "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      }, "type": "review", "id": 1, "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature", "id": 10
      }]
    }, {
      "campaignName": "Vild Med Film 2016", "startDate": "2016-07-15T22:00:00.000Z",
      "endDate": "2016-09-30T21:59:59.000Z", "logos": {
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=BjJ1xzJ8",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=emXGcxp5",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/VildmedfilmLOGO_no%20background.png?itok=OyLHdCzn",
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/VildmedfilmLOGO%20solid.svg"
      }, "type": "review", "id": 2, "workTypes": [{"worktype": "movie", "id": 6}]
    }, {
      "campaignName": "Sommerbogen 2017", "startDate": "2017-06-12T22:00:00.000Z",
      "endDate": "2017-08-26T21:59:59.000Z", "logos": {
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/sommerbogen-logo.svg",
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=5f95nbCt",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=aAgdIqi0",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/Sommerbogen%20logo.png?itok=kI0CJooV"
      }, "type": "review", "id": 10, "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "other", "id": 4}, {
        "worktype": "audiobook", "id": 7
      }, {"worktype": "literature", "id": 10}]
    }, {
      "campaignName": "Vild med film 2017", "startDate": "2017-08-31T22:00:00.000Z",
      "endDate": "2017-09-21T21:59:59.000Z", "logos": {
        "svg": "http://admin.biblo.dk/sites/default/files/campaigns/logos/svg/VildmedfilmLOGO%20solid_0.svg",
        "small": "http://admin.biblo.dk/sites/default/files/styles/small/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=ovrp6MLC",
        "medium": "http://admin.biblo.dk/sites/default/files/styles/medium/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=ntb0gLew",
        "large": "http://admin.biblo.dk/sites/default/files/styles/large/public/campaigns/logos/img/VildmedfilmLOGO_no%20background_0.png?itok=Hs5ErkZ7"
      }, "type": "review", "id": 11, "workTypes": [{"worktype": "movie", "id": 6}]
    }]);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({
      "access_token": "",
      "where": "{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29410895\"},{\"pid\":\"870970-basis:29926492\"}]}]}"
    })
    .reply(200, {"count": 0});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29410895\"},{\"pid\":\"870970-basis:29926492\"}]}]}}"})
    .reply(200, []);
};
