// Autogenerated!
const nock = require('nock'); 
module.exports = function LegoIndianaJones (times) {
                nock('http://localhost:3000', {encodedQueryParams: true})
                  .get('/api/reviews/count')
                  .times(times)
                  .query({"access_token":"","where":"{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29186626\"},{\"pid\":\"870970-basis:27312381\"},{\"pid\":\"870970-basis:27364616\"},{\"pid\":\"870970-basis:27312438\"},{\"pid\":\"870970-basis:27312462\"},{\"pid\":\"870970-basis:27312497\"}]}]}"})
                  .reply(200, {"count":0});

                nock('http://localhost:3000', {encodedQueryParams: true})
                  .get('/api/reviews/')
                  .times(times)
                  .query({"filter":"{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29186626\"},{\"pid\":\"870970-basis:27312381\"},{\"pid\":\"870970-basis:27364616\"},{\"pid\":\"870970-basis:27312438\"},{\"pid\":\"870970-basis:27312462\"},{\"pid\":\"870970-basis:27312497\"}]}]}}"})
                  .reply(200, []);

                nock('http://localhost:3000', {encodedQueryParams: true})
                  .get('/api/Campaigns')
                  .times(times)
                  .query({"filter":"{\"where\":{\"type\":\"review\"}}"})
                  .reply(200, [{"campaignName":"Sommerbogen 2016","startDate":"2016-06-09T20:00:00.044Z","endDate":"2016-08-21T04:00:00.044Z","logos":{"svg":"/sommerbogen-logo.svg","small":"/sommerbogen-logo.png","medium":"/sommerbogen-logo.png","large":"/sommerbogen-logo.png"},"type":"review","id":1,"workTypes":[{"worktype":"book","id":1},{"worktype":"audiobook","id":7},{"worktype":"literature","id":10}]}]);};
