// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function LegoIndianaJones(times) {
  nock('http://platform-i01.dbc.dk:8080', {encodedQueryParams: true})
    .post('/v1/work/')
    .times(times)

    .reply(200, {
      "statusCode": 200,
      "data": [{
        "dcTitle": ["Lego Indiana Jones - the original adventures"],
        "dcTitleFull": ["Lego Indiana Jones - the original adventures (Nintendo DS)"],
        "publisher": ["LucasArts"],
        "description": ["Titlen hentet fra kassetteetiketten", "Instruction booklet: Engelsk tekst"],
        "format": ["1 kassette, Nintendo DS, lyd, farve, 1 instruction booklet", "Afspilningsudstyr Nintendo DS. - Med multiplayerfunktion"],
        "collection": ["870970-basis:29186626", "870970-basis:27312381", "870970-basis:27364616", "870970-basis:27312438", "870970-basis:27312462", "870970-basis:27312497"],
        "collectionDetails": [{
          "accessType": ["physical"],
          "pid": ["870970-basis:29186626"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Nintendo DS"],
          "workType": ["game"]
        }, {
          "accessType": ["physical"],
          "pid": ["870970-basis:27312381"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Pc-spil"],
          "workType": ["game"]
        }, {
          "accessType": ["physical"],
          "pid": ["870970-basis:27364616"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Playstation 2"],
          "workType": ["game"]
        }, {
          "accessType": ["physical"],
          "pid": ["870970-basis:27312438"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Playstation 3"],
          "workType": ["game"]
        }, {
          "accessType": ["physical"],
          "pid": ["870970-basis:27312462"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Wii"],
          "workType": ["game"]
        }, {
          "accessType": ["physical"],
          "pid": ["870970-basis:27312497"],
          "title": ["Lego Indiana Jones - the original adventures"],
          "titleFull": ["Lego Indiana Jones - the original adventures"],
          "type": ["Xbox 360"],
          "workType": ["game"]
        }],
        "coverUrlFull": ["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=29186626&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=dbc6d3d045e41804d403"],
        "dcLanguage": ["Flere sprog", "Dansk", "Engelsk", "Tysk", "Fransk", "Spansk", "Italiensk"],
        "accessType": ["physical"],
        "audienceAge": ["Fra 5 år"],
        "audience": ["børnematerialer"],
        "audiencePegi": ["PEGI-mærkning: 7"],
        "subjectDK5": ["79.41"],
        "subjectDK5Text": ["Computerspil"],
        "contributor": ["Paul Hughes (programmør)", "Phil Owen", "Nolan Worthington", "TT Fusion"],
        "workType": ["game"],
        "type": ["Nintendo DS"],
        "date": ["2008"]
      }]
    });

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({
      "access_token": "",
      "where": "{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29186626\"},{\"pid\":\"870970-basis:27312381\"},{\"pid\":\"870970-basis:27364616\"},{\"pid\":\"870970-basis:27312438\"},{\"pid\":\"870970-basis:27312462\"},{\"pid\":\"870970-basis:27312497\"}]}]}"
    })
    .reply(200, {"count": 0});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:29186626\"},{\"pid\":\"870970-basis:27312381\"},{\"pid\":\"870970-basis:27364616\"},{\"pid\":\"870970-basis:27312438\"},{\"pid\":\"870970-basis:27312462\"},{\"pid\":\"870970-basis:27312497\"}]}]}}"})
    .reply(200, []);

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/Campaigns')
    .times(times)
    .query({"filter": "{\"where\":{\"type\":\"review\"},\"include\":[]}"})
    .reply(200, [{
      "campaignName": "Sommerbogen 2016",
      "startDate": "2016-06-09T20:00:00.044Z",
      "endDate": "2016-08-21T04:00:00.044Z",
      "logos": {
        "svg": "/sommerbogen-logo.svg",
        "small": "/sommerbogen-logo.png",
        "medium": "/sommerbogen-logo.png",
        "large": "/sommerbogen-logo.png"
      },
      "type": "review",
      "id": 1,
      "workTypes": [{"worktype": "book", "id": 1}, {"worktype": "audiobook", "id": 7}, {
        "worktype": "literature",
        "id": 10
      }]
    }]);
};
