// Autogenerated!
/* eslint-disable */
const nock = require('nock');
module.exports = function peterpedal (times) {
  nock('http://platform-i01:8080', {encodedQueryParams: true})
  .post('/work/')
  .times(times)
  .reply(200, {"statusCode":200,"data":[{"dcTitle":["Peter Pedal"],"dcTitleFull":["Peter Pedal"],"titleSeries":["Peter-Pedal-bøgerne"],"publisher":["Gyldendal"],"extent":["45 sider"],"format":["alle illustreret i farver"],"collection":["870970-basis:27889654","870970-basis:05074975"],"collectionDetails":[{"accessType":["physical"],"creator":["H. A. Rey"],"pid":["870970-basis:27889654"],"language":["Dansk"],"title":["Peter Pedal"],"titleFull":["Peter Pedal"],"type":["Billedbog"],"workType":["book"]},{"accessType":["physical"],"creator":["H. A. Rey"],"pid":["870970-basis:05074975"],"language":["Dansk"],"title":["Peter Pedal"],"titleFull":["Peter Pedal"],"type":["Billedbog"],"workType":["book"]}],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05074975&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=3dde9d66cea2c25ae810"],"dcLanguage":["Dansk"],"accessType":["physical"],"audienceAge":["fra 3 år"],"audience":["børnematerialer"],"subjectDK5":["sk"],"subjectDK5Text":["Skønlitteratur"],"subjectDBCN":["for 3 år","for 4 år","for 5 år","for 6 år"],"subjectDBCS":["aber","sjove bøger"],"creator":["H. A. Rey"],"creatorAut":["H. A. Rey"],"creatorSort":["Rey, H. A."],"abstract":["Billedbog. Aben Peter er vældig nysgerrig. En dag får han en cykel foræret. Han får tilnavnet Pedal mod at dele aviserne ud for avisbudet, men nysgerrigheden bringer Peter Pedal på afveje"],"workType":["book"],"type":["Billedbog"],"date":["1957"]}]});

  nock('http://localhost:3000', {encodedQueryParams: true})
  .get('/api/reviews/count')
  .times(times)
  .query({"access_token":"","where":"{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05074975\"}]}]}"})
  .reply(200, {"count":0});

  nock('http://localhost:3000', {encodedQueryParams: true})
  .get('/api/reviews/')
  .times(times)
  .query({"filter":"{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05074975\"}]}]}}"})
  .reply(200, []);

  nock('http://localhost:3000', {encodedQueryParams: true})
  .get('/api/Campaigns')
  .times(times)
  .query({"filter":"{\"where\":{\"type\":\"review\"},\"include\":[]}"})
  .reply(200, [{"campaignName":"Sommerbogen 2016","startDate":"2016-06-09T20:00:00.044Z","endDate":"2016-08-21T04:00:00.044Z","logos":{"svg":"/sommerbogen-logo.svg","small":"/sommerbogen-logo.png","medium":"/sommerbogen-logo.png","large":"/sommerbogen-logo.png"},"type":"review","id":1,"workTypes":[{"worktype":"book","id":1},{"worktype":"audiobook","id":7},{"worktype":"literature","id":10}]}]);

  nock('http://platform-i01:8080', {encodedQueryParams: true})
  .post('/search/?q=%28%22%2A%22%29%20AND%20%28phrase.titleSeries%3D%22Peter-Pedal-b%C3%B8gerne%22%29&fields%5B0%5D=pid&fields%5B1%5D=coverUrlFull&fields%5B2%5D=dcTitle&fields%5B3%5D=titleSeries&limit=6&offset=0&sort=solr_numberInSeries_ascending')
  .times(times)
  .reply(200, {"statusCode":200,"data":[{"pid":["870970-basis:05000319"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05000319&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ce0784207fc2469a4343"],"dcTitle":["Peter Pedal på hospital"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:05074975"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05074975&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=3dde9d66cea2c25ae810"],"dcTitle":["Peter Pedal"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:21504904"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=21504904&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ab40734e0f66ec4a97b4"],"dcTitle":["Peter Pedal sætter drage op"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:05131499"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05131499&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=bf8a01837081ff78710e"],"dcTitle":["Peter Pedal hænger i"],"titleSeries":["Peter-Pedal-bøgerne"]}]});

  nock('http://platform-i01:8080', {encodedQueryParams: true})
    .post('/search/?q=%28%22%2A%22%29%20AND%20%28phrase.titleSeries%3D%22Peter-Pedal-b%C3%B8gerne%22%29&fields%5B0%5D=pid&fields%5B1%5D=coverUrlFull&fields%5B2%5D=dcTitle&fields%5B3%5D=titleSeries&fields%5B4%5D=workType&limit=18&offset=0&sort=solr_numberInSeries_ascending')
    .times(times)
    .reply(200, {"statusCode":200,"data":[{"pid":["870970-basis:05000319"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05000319&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ce0784207fc2469a4343"],"dcTitle":["Peter Pedal på hospital"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:05074975"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05074975&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=3dde9d66cea2c25ae810"],"dcTitle":["Peter Pedal"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:21504904"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=21504904&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ab40734e0f66ec4a97b4"],"dcTitle":["Peter Pedal sætter drage op"],"titleSeries":["Peter-Pedal-bøgerne"]},{"pid":["870970-basis:05131499"],"coverUrlFull":["//moreinfo.addi.dk/2.6/more_info_get.php?lokalid=05131499&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=bf8a01837081ff78710e"],"dcTitle":["Peter Pedal hænger i"],"titleSeries":["Peter-Pedal-bøgerne"]}]});
};
