// Autogenerated!
const nock = require('nock');
module.exports = function peterpedal(times) {
  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/count')
    .times(times)
    .query({
      "access_token": "",
      "where": "{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05074975\"},{\"pid\":\"870970-basis:27889654\"}]}]}"
    })
    .reply(200, {"count": 4});

  nock('http://localhost:3000', {encodedQueryParams: true})
    .get('/api/reviews/')
    .times(times)
    .query({"filter": "{\"skip\":0,\"limit\":10,\"order\":\"created DESC\",\"include\":[\"likes\",\"image\",{\"relation\":\"video\",\"scope\":{\"include\":[{\"relation\":\"resolutions\",\"scope\":{\"include\":[\"video\"]}}]}},{\"relation\":\"owner\",\"scope\":{\"include\":[\"image\"]}}],\"where\":{\"and\":[{\"markedAsDeleted\":null},{\"or\":[{\"pid\":\"870970-basis:05074975\"},{\"pid\":\"870970-basis:27889654\"}]}]}}"})
    .reply(200, [{
      "pid": "870970-basis:05074975",
      "libraryid": "726502",
      "worktype": "book",
      "content": "jeg har lige læst en bog der hedder peter pedal den handler om en lille abe der er meget nysgerrig den er skrevet af Margret og H.A. Rey. Jeg synes bogen den er sjov god, og jeg synes at I skulle læse den.",
      "created": "2016-06-23T18:38:14.000Z",
      "modified": "2016-06-23T18:38:14.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": null,
      "id": 67063,
      "reviewownerid": 46122,
      "likes": [],
      "owner": {}
    }, {
      "pid": "870970-basis:05074975",
      "libraryid": "726500",
      "worktype": "literature",
      "content": "Peter pedal får en cykel af manden med den gule hat. Så siger manden at de skal i cirkus om aftenen. Da  Peter cykler går cyklen i stykker så han må køre på baghjulet det ser cirkusdirektøren og spørger om han vil optræde i cirkus.\nPeter lytter aldrig til manden med den gule hat og kommer galt af sted. Det er sjove og spændende historier.",
      "created": "2014-08-06T22:00:00.000Z",
      "modified": "2014-08-06T22:00:00.000Z",
      "rating": 6,
      "markedAsDeleted": null,
      "palleid": 53865,
      "id": 47415,
      "reviewownerid": 27936,
      "likes": [],
      "owner": {}
    }, {
      "pid": "870970-basis:05074975",
      "libraryid": "724001",
      "worktype": "literature",
      "content": "Den handler om en abe der hedder Peter Pedal. Han får sin egen cykel og han kan lave tricks på den. Han er også i cirkus. Han kører rundt på sin cykel kun på baghjulet. Den er lidt kort 48 sider. Jeg synes den er nem at læse. ",
      "created": "2014-07-04T22:00:00.000Z",
      "modified": "2014-07-04T22:00:00.000Z",
      "rating": 5,
      "markedAsDeleted": null,
      "palleid": 46717,
      "id": 40333,
      "reviewownerid": 27426,
      "likes": [],
      "owner": {}
    }, {
      "pid": "870970-basis:05074975",
      "libraryid": "726500",
      "worktype": "literature",
      "content": "Peter Pedal sidder og spisser morgen mad med sin ven med den gule hat.  Manden med den gule hat havde en overraskelse til Peter og overraskelsen var en cykel. Men nu skulle manden med den gule hat på ajbergte. Peter kørte på sin cykel og på vejen møtte han avis drengen og avis drengen spurte om han ikke nok vil dele aviserne ud for ham og det ville Peter rigdig gerne. Men pludselig ville han heller fiske og lave salbåde med avisser nede ved søen. Men han havde glemt af dele aviserne ud. han cyklede vidrer da han var færti med af lave salbåde men ligepluselig kørte han ind i en sten hans dæk bleev flat men manden med den gule hat lavede det og bagefter to de i cirkus. ",
      "created": "2013-08-13T22:00:00.000Z",
      "modified": "2013-08-13T22:00:00.000Z",
      "rating": 4,
      "markedAsDeleted": null,
      "palleid": 40047,
      "id": 33792,
      "reviewownerid": 17677,
      "likes": [],
      "owner": {}
    }]);
};
